// Code generated by protoc-gen-go. DO NOT EDIT.
// source: BasicApi.proto

package dfproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetWorldInfoOut_Mode int32

const (
	GetWorldInfoOut_MODE_DWARF     GetWorldInfoOut_Mode = 1
	GetWorldInfoOut_MODE_ADVENTURE GetWorldInfoOut_Mode = 2
	GetWorldInfoOut_MODE_LEGENDS   GetWorldInfoOut_Mode = 3
)

var GetWorldInfoOut_Mode_name = map[int32]string{
	1: "MODE_DWARF",
	2: "MODE_ADVENTURE",
	3: "MODE_LEGENDS",
}
var GetWorldInfoOut_Mode_value = map[string]int32{
	"MODE_DWARF":     1,
	"MODE_ADVENTURE": 2,
	"MODE_LEGENDS":   3,
}

func (x GetWorldInfoOut_Mode) Enum() *GetWorldInfoOut_Mode {
	p := new(GetWorldInfoOut_Mode)
	*p = x
	return p
}
func (x GetWorldInfoOut_Mode) String() string {
	return proto.EnumName(GetWorldInfoOut_Mode_name, int32(x))
}
func (x *GetWorldInfoOut_Mode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetWorldInfoOut_Mode_value, data, "GetWorldInfoOut_Mode")
	if err != nil {
		return err
	}
	*x = GetWorldInfoOut_Mode(value)
	return nil
}
func (GetWorldInfoOut_Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_BasicApi_38d5d50881d2f891, []int{0, 0}
}

// RPC GetWorldInfo : EmptyMessage -> GetWorldInfoOut
type GetWorldInfoOut struct {
	Mode      *GetWorldInfoOut_Mode `protobuf:"varint,1,req,name=mode,enum=dfproto.GetWorldInfoOut_Mode" json:"mode,omitempty"`
	SaveDir   *string               `protobuf:"bytes,2,req,name=save_dir,json=saveDir" json:"save_dir,omitempty"`
	WorldName *NameInfo             `protobuf:"bytes,3,opt,name=world_name,json=worldName" json:"world_name,omitempty"`
	// Dwarf mode
	CivId   *int32 `protobuf:"varint,4,opt,name=civ_id,json=civId" json:"civ_id,omitempty"`
	SiteId  *int32 `protobuf:"varint,5,opt,name=site_id,json=siteId" json:"site_id,omitempty"`
	GroupId *int32 `protobuf:"varint,6,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	RaceId  *int32 `protobuf:"varint,7,opt,name=race_id,json=raceId" json:"race_id,omitempty"`
	// Adventure mode
	PlayerUnitId         *int32   `protobuf:"varint,8,opt,name=player_unit_id,json=playerUnitId" json:"player_unit_id,omitempty"`
	PlayerHistfigId      *int32   `protobuf:"varint,9,opt,name=player_histfig_id,json=playerHistfigId" json:"player_histfig_id,omitempty"`
	CompanionHistfigIds  []int32  `protobuf:"varint,10,rep,name=companion_histfig_ids,json=companionHistfigIds" json:"companion_histfig_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorldInfoOut) Reset()         { *m = GetWorldInfoOut{} }
func (m *GetWorldInfoOut) String() string { return proto.CompactTextString(m) }
func (*GetWorldInfoOut) ProtoMessage()    {}
func (*GetWorldInfoOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_BasicApi_38d5d50881d2f891, []int{0}
}
func (m *GetWorldInfoOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorldInfoOut.Unmarshal(m, b)
}
func (m *GetWorldInfoOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorldInfoOut.Marshal(b, m, deterministic)
}
func (dst *GetWorldInfoOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorldInfoOut.Merge(dst, src)
}
func (m *GetWorldInfoOut) XXX_Size() int {
	return xxx_messageInfo_GetWorldInfoOut.Size(m)
}
func (m *GetWorldInfoOut) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorldInfoOut.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorldInfoOut proto.InternalMessageInfo

func (m *GetWorldInfoOut) GetMode() GetWorldInfoOut_Mode {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return GetWorldInfoOut_MODE_DWARF
}

func (m *GetWorldInfoOut) GetSaveDir() string {
	if m != nil && m.SaveDir != nil {
		return *m.SaveDir
	}
	return ""
}

func (m *GetWorldInfoOut) GetWorldName() *NameInfo {
	if m != nil {
		return m.WorldName
	}
	return nil
}

func (m *GetWorldInfoOut) GetCivId() int32 {
	if m != nil && m.CivId != nil {
		return *m.CivId
	}
	return 0
}

func (m *GetWorldInfoOut) GetSiteId() int32 {
	if m != nil && m.SiteId != nil {
		return *m.SiteId
	}
	return 0
}

func (m *GetWorldInfoOut) GetGroupId() int32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GetWorldInfoOut) GetRaceId() int32 {
	if m != nil && m.RaceId != nil {
		return *m.RaceId
	}
	return 0
}

func (m *GetWorldInfoOut) GetPlayerUnitId() int32 {
	if m != nil && m.PlayerUnitId != nil {
		return *m.PlayerUnitId
	}
	return 0
}

func (m *GetWorldInfoOut) GetPlayerHistfigId() int32 {
	if m != nil && m.PlayerHistfigId != nil {
		return *m.PlayerHistfigId
	}
	return 0
}

func (m *GetWorldInfoOut) GetCompanionHistfigIds() []int32 {
	if m != nil {
		return m.CompanionHistfigIds
	}
	return nil
}

// RPC ListEnums : EmptyMessage -> ListEnumsOut
type ListEnumsOut struct {
	MaterialFlags        []*EnumItemName `protobuf:"bytes,1,rep,name=material_flags,json=materialFlags" json:"material_flags,omitempty"`
	InorganicFlags       []*EnumItemName `protobuf:"bytes,2,rep,name=inorganic_flags,json=inorganicFlags" json:"inorganic_flags,omitempty"`
	UnitFlags1           []*EnumItemName `protobuf:"bytes,3,rep,name=unit_flags1,json=unitFlags1" json:"unit_flags1,omitempty"`
	UnitFlags2           []*EnumItemName `protobuf:"bytes,4,rep,name=unit_flags2,json=unitFlags2" json:"unit_flags2,omitempty"`
	UnitFlags3           []*EnumItemName `protobuf:"bytes,5,rep,name=unit_flags3,json=unitFlags3" json:"unit_flags3,omitempty"`
	UnitLabor            []*EnumItemName `protobuf:"bytes,6,rep,name=unit_labor,json=unitLabor" json:"unit_labor,omitempty"`
	JobSkill             []*EnumItemName `protobuf:"bytes,7,rep,name=job_skill,json=jobSkill" json:"job_skill,omitempty"`
	CieAddTagMask1       []*EnumItemName `protobuf:"bytes,8,rep,name=cie_add_tag_mask1,json=cieAddTagMask1" json:"cie_add_tag_mask1,omitempty"`
	CieAddTagMask2       []*EnumItemName `protobuf:"bytes,9,rep,name=cie_add_tag_mask2,json=cieAddTagMask2" json:"cie_add_tag_mask2,omitempty"`
	DeathInfoFlags       []*EnumItemName `protobuf:"bytes,10,rep,name=death_info_flags,json=deathInfoFlags" json:"death_info_flags,omitempty"`
	Profession           []*EnumItemName `protobuf:"bytes,11,rep,name=profession" json:"profession,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListEnumsOut) Reset()         { *m = ListEnumsOut{} }
func (m *ListEnumsOut) String() string { return proto.CompactTextString(m) }
func (*ListEnumsOut) ProtoMessage()    {}
func (*ListEnumsOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_BasicApi_38d5d50881d2f891, []int{1}
}
func (m *ListEnumsOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEnumsOut.Unmarshal(m, b)
}
func (m *ListEnumsOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEnumsOut.Marshal(b, m, deterministic)
}
func (dst *ListEnumsOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEnumsOut.Merge(dst, src)
}
func (m *ListEnumsOut) XXX_Size() int {
	return xxx_messageInfo_ListEnumsOut.Size(m)
}
func (m *ListEnumsOut) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEnumsOut.DiscardUnknown(m)
}

var xxx_messageInfo_ListEnumsOut proto.InternalMessageInfo

func (m *ListEnumsOut) GetMaterialFlags() []*EnumItemName {
	if m != nil {
		return m.MaterialFlags
	}
	return nil
}

func (m *ListEnumsOut) GetInorganicFlags() []*EnumItemName {
	if m != nil {
		return m.InorganicFlags
	}
	return nil
}

func (m *ListEnumsOut) GetUnitFlags1() []*EnumItemName {
	if m != nil {
		return m.UnitFlags1
	}
	return nil
}

func (m *ListEnumsOut) GetUnitFlags2() []*EnumItemName {
	if m != nil {
		return m.UnitFlags2
	}
	return nil
}

func (m *ListEnumsOut) GetUnitFlags3() []*EnumItemName {
	if m != nil {
		return m.UnitFlags3
	}
	return nil
}

func (m *ListEnumsOut) GetUnitLabor() []*EnumItemName {
	if m != nil {
		return m.UnitLabor
	}
	return nil
}

func (m *ListEnumsOut) GetJobSkill() []*EnumItemName {
	if m != nil {
		return m.JobSkill
	}
	return nil
}

func (m *ListEnumsOut) GetCieAddTagMask1() []*EnumItemName {
	if m != nil {
		return m.CieAddTagMask1
	}
	return nil
}

func (m *ListEnumsOut) GetCieAddTagMask2() []*EnumItemName {
	if m != nil {
		return m.CieAddTagMask2
	}
	return nil
}

func (m *ListEnumsOut) GetDeathInfoFlags() []*EnumItemName {
	if m != nil {
		return m.DeathInfoFlags
	}
	return nil
}

func (m *ListEnumsOut) GetProfession() []*EnumItemName {
	if m != nil {
		return m.Profession
	}
	return nil
}

// RPC ListJobSkills : EmptyMessage -> ListJobSkillsOut
type ListJobSkillsOut struct {
	Skill                []*JobSkillAttr   `protobuf:"bytes,1,rep,name=skill" json:"skill,omitempty"`
	Profession           []*ProfessionAttr `protobuf:"bytes,2,rep,name=profession" json:"profession,omitempty"`
	Labor                []*UnitLaborAttr  `protobuf:"bytes,3,rep,name=labor" json:"labor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListJobSkillsOut) Reset()         { *m = ListJobSkillsOut{} }
func (m *ListJobSkillsOut) String() string { return proto.CompactTextString(m) }
func (*ListJobSkillsOut) ProtoMessage()    {}
func (*ListJobSkillsOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_BasicApi_38d5d50881d2f891, []int{2}
}
func (m *ListJobSkillsOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobSkillsOut.Unmarshal(m, b)
}
func (m *ListJobSkillsOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobSkillsOut.Marshal(b, m, deterministic)
}
func (dst *ListJobSkillsOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobSkillsOut.Merge(dst, src)
}
func (m *ListJobSkillsOut) XXX_Size() int {
	return xxx_messageInfo_ListJobSkillsOut.Size(m)
}
func (m *ListJobSkillsOut) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobSkillsOut.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobSkillsOut proto.InternalMessageInfo

func (m *ListJobSkillsOut) GetSkill() []*JobSkillAttr {
	if m != nil {
		return m.Skill
	}
	return nil
}

func (m *ListJobSkillsOut) GetProfession() []*ProfessionAttr {
	if m != nil {
		return m.Profession
	}
	return nil
}

func (m *ListJobSkillsOut) GetLabor() []*UnitLaborAttr {
	if m != nil {
		return m.Labor
	}
	return nil
}

// RPC ListMaterials : ListMaterialsIn -> ListMaterialsOut
type ListMaterialsIn struct {
	Mask *BasicMaterialInfoMask `protobuf:"bytes,1,opt,name=mask" json:"mask,omitempty"`
	// Specific materials:
	IdList []*BasicMaterialId `protobuf:"bytes,2,rep,name=id_list,json=idList" json:"id_list,omitempty"`
	// Complete list by type:
	Builtin              *bool    `protobuf:"varint,3,opt,name=builtin" json:"builtin,omitempty"`
	Inorganic            *bool    `protobuf:"varint,4,opt,name=inorganic" json:"inorganic,omitempty"`
	Creatures            *bool    `protobuf:"varint,5,opt,name=creatures" json:"creatures,omitempty"`
	Plants               *bool    `protobuf:"varint,6,opt,name=plants" json:"plants,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMaterialsIn) Reset()         { *m = ListMaterialsIn{} }
func (m *ListMaterialsIn) String() string { return proto.CompactTextString(m) }
func (*ListMaterialsIn) ProtoMessage()    {}
func (*ListMaterialsIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_BasicApi_38d5d50881d2f891, []int{3}
}
func (m *ListMaterialsIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMaterialsIn.Unmarshal(m, b)
}
func (m *ListMaterialsIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMaterialsIn.Marshal(b, m, deterministic)
}
func (dst *ListMaterialsIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMaterialsIn.Merge(dst, src)
}
func (m *ListMaterialsIn) XXX_Size() int {
	return xxx_messageInfo_ListMaterialsIn.Size(m)
}
func (m *ListMaterialsIn) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMaterialsIn.DiscardUnknown(m)
}

var xxx_messageInfo_ListMaterialsIn proto.InternalMessageInfo

func (m *ListMaterialsIn) GetMask() *BasicMaterialInfoMask {
	if m != nil {
		return m.Mask
	}
	return nil
}

func (m *ListMaterialsIn) GetIdList() []*BasicMaterialId {
	if m != nil {
		return m.IdList
	}
	return nil
}

func (m *ListMaterialsIn) GetBuiltin() bool {
	if m != nil && m.Builtin != nil {
		return *m.Builtin
	}
	return false
}

func (m *ListMaterialsIn) GetInorganic() bool {
	if m != nil && m.Inorganic != nil {
		return *m.Inorganic
	}
	return false
}

func (m *ListMaterialsIn) GetCreatures() bool {
	if m != nil && m.Creatures != nil {
		return *m.Creatures
	}
	return false
}

func (m *ListMaterialsIn) GetPlants() bool {
	if m != nil && m.Plants != nil {
		return *m.Plants
	}
	return false
}

type ListMaterialsOut struct {
	Value                []*BasicMaterialInfo `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListMaterialsOut) Reset()         { *m = ListMaterialsOut{} }
func (m *ListMaterialsOut) String() string { return proto.CompactTextString(m) }
func (*ListMaterialsOut) ProtoMessage()    {}
func (*ListMaterialsOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_BasicApi_38d5d50881d2f891, []int{4}
}
func (m *ListMaterialsOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMaterialsOut.Unmarshal(m, b)
}
func (m *ListMaterialsOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMaterialsOut.Marshal(b, m, deterministic)
}
func (dst *ListMaterialsOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMaterialsOut.Merge(dst, src)
}
func (m *ListMaterialsOut) XXX_Size() int {
	return xxx_messageInfo_ListMaterialsOut.Size(m)
}
func (m *ListMaterialsOut) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMaterialsOut.DiscardUnknown(m)
}

var xxx_messageInfo_ListMaterialsOut proto.InternalMessageInfo

func (m *ListMaterialsOut) GetValue() []*BasicMaterialInfo {
	if m != nil {
		return m.Value
	}
	return nil
}

// RPC ListUnits : ListUnitsIn -> ListUnitsOut
type ListUnitsIn struct {
	Mask *BasicUnitInfoMask `protobuf:"bytes,1,opt,name=mask" json:"mask,omitempty"`
	// Specific units:
	IdList []int32 `protobuf:"varint,2,rep,name=id_list,json=idList" json:"id_list,omitempty"`
	// All units matching:
	ScanAll              *bool    `protobuf:"varint,5,opt,name=scan_all,json=scanAll" json:"scan_all,omitempty"`
	Race                 *int32   `protobuf:"varint,3,opt,name=race" json:"race,omitempty"`
	CivId                *int32   `protobuf:"varint,4,opt,name=civ_id,json=civId" json:"civ_id,omitempty"`
	Dead                 *bool    `protobuf:"varint,6,opt,name=dead" json:"dead,omitempty"`
	Alive                *bool    `protobuf:"varint,7,opt,name=alive" json:"alive,omitempty"`
	Sane                 *bool    `protobuf:"varint,8,opt,name=sane" json:"sane,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUnitsIn) Reset()         { *m = ListUnitsIn{} }
func (m *ListUnitsIn) String() string { return proto.CompactTextString(m) }
func (*ListUnitsIn) ProtoMessage()    {}
func (*ListUnitsIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_BasicApi_38d5d50881d2f891, []int{5}
}
func (m *ListUnitsIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUnitsIn.Unmarshal(m, b)
}
func (m *ListUnitsIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUnitsIn.Marshal(b, m, deterministic)
}
func (dst *ListUnitsIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUnitsIn.Merge(dst, src)
}
func (m *ListUnitsIn) XXX_Size() int {
	return xxx_messageInfo_ListUnitsIn.Size(m)
}
func (m *ListUnitsIn) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUnitsIn.DiscardUnknown(m)
}

var xxx_messageInfo_ListUnitsIn proto.InternalMessageInfo

func (m *ListUnitsIn) GetMask() *BasicUnitInfoMask {
	if m != nil {
		return m.Mask
	}
	return nil
}

func (m *ListUnitsIn) GetIdList() []int32 {
	if m != nil {
		return m.IdList
	}
	return nil
}

func (m *ListUnitsIn) GetScanAll() bool {
	if m != nil && m.ScanAll != nil {
		return *m.ScanAll
	}
	return false
}

func (m *ListUnitsIn) GetRace() int32 {
	if m != nil && m.Race != nil {
		return *m.Race
	}
	return 0
}

func (m *ListUnitsIn) GetCivId() int32 {
	if m != nil && m.CivId != nil {
		return *m.CivId
	}
	return 0
}

func (m *ListUnitsIn) GetDead() bool {
	if m != nil && m.Dead != nil {
		return *m.Dead
	}
	return false
}

func (m *ListUnitsIn) GetAlive() bool {
	if m != nil && m.Alive != nil {
		return *m.Alive
	}
	return false
}

func (m *ListUnitsIn) GetSane() bool {
	if m != nil && m.Sane != nil {
		return *m.Sane
	}
	return false
}

type ListUnitsOut struct {
	Value                []*BasicUnitInfo `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListUnitsOut) Reset()         { *m = ListUnitsOut{} }
func (m *ListUnitsOut) String() string { return proto.CompactTextString(m) }
func (*ListUnitsOut) ProtoMessage()    {}
func (*ListUnitsOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_BasicApi_38d5d50881d2f891, []int{6}
}
func (m *ListUnitsOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUnitsOut.Unmarshal(m, b)
}
func (m *ListUnitsOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUnitsOut.Marshal(b, m, deterministic)
}
func (dst *ListUnitsOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUnitsOut.Merge(dst, src)
}
func (m *ListUnitsOut) XXX_Size() int {
	return xxx_messageInfo_ListUnitsOut.Size(m)
}
func (m *ListUnitsOut) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUnitsOut.DiscardUnknown(m)
}

var xxx_messageInfo_ListUnitsOut proto.InternalMessageInfo

func (m *ListUnitsOut) GetValue() []*BasicUnitInfo {
	if m != nil {
		return m.Value
	}
	return nil
}

// RPC ListSquads : ListSquadsIn -> ListSquadsOut
type ListSquadsIn struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSquadsIn) Reset()         { *m = ListSquadsIn{} }
func (m *ListSquadsIn) String() string { return proto.CompactTextString(m) }
func (*ListSquadsIn) ProtoMessage()    {}
func (*ListSquadsIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_BasicApi_38d5d50881d2f891, []int{7}
}
func (m *ListSquadsIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSquadsIn.Unmarshal(m, b)
}
func (m *ListSquadsIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSquadsIn.Marshal(b, m, deterministic)
}
func (dst *ListSquadsIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSquadsIn.Merge(dst, src)
}
func (m *ListSquadsIn) XXX_Size() int {
	return xxx_messageInfo_ListSquadsIn.Size(m)
}
func (m *ListSquadsIn) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSquadsIn.DiscardUnknown(m)
}

var xxx_messageInfo_ListSquadsIn proto.InternalMessageInfo

type ListSquadsOut struct {
	Value                []*BasicSquadInfo `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListSquadsOut) Reset()         { *m = ListSquadsOut{} }
func (m *ListSquadsOut) String() string { return proto.CompactTextString(m) }
func (*ListSquadsOut) ProtoMessage()    {}
func (*ListSquadsOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_BasicApi_38d5d50881d2f891, []int{8}
}
func (m *ListSquadsOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSquadsOut.Unmarshal(m, b)
}
func (m *ListSquadsOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSquadsOut.Marshal(b, m, deterministic)
}
func (dst *ListSquadsOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSquadsOut.Merge(dst, src)
}
func (m *ListSquadsOut) XXX_Size() int {
	return xxx_messageInfo_ListSquadsOut.Size(m)
}
func (m *ListSquadsOut) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSquadsOut.DiscardUnknown(m)
}

var xxx_messageInfo_ListSquadsOut proto.InternalMessageInfo

func (m *ListSquadsOut) GetValue() []*BasicSquadInfo {
	if m != nil {
		return m.Value
	}
	return nil
}

// RPC SetUnitLabors : SetUnitLaborsIn -> EmptyMessage
type SetUnitLaborsIn struct {
	Change               []*UnitLaborState `protobuf:"bytes,1,rep,name=change" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetUnitLaborsIn) Reset()         { *m = SetUnitLaborsIn{} }
func (m *SetUnitLaborsIn) String() string { return proto.CompactTextString(m) }
func (*SetUnitLaborsIn) ProtoMessage()    {}
func (*SetUnitLaborsIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_BasicApi_38d5d50881d2f891, []int{9}
}
func (m *SetUnitLaborsIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUnitLaborsIn.Unmarshal(m, b)
}
func (m *SetUnitLaborsIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUnitLaborsIn.Marshal(b, m, deterministic)
}
func (dst *SetUnitLaborsIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUnitLaborsIn.Merge(dst, src)
}
func (m *SetUnitLaborsIn) XXX_Size() int {
	return xxx_messageInfo_SetUnitLaborsIn.Size(m)
}
func (m *SetUnitLaborsIn) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUnitLaborsIn.DiscardUnknown(m)
}

var xxx_messageInfo_SetUnitLaborsIn proto.InternalMessageInfo

func (m *SetUnitLaborsIn) GetChange() []*UnitLaborState {
	if m != nil {
		return m.Change
	}
	return nil
}

func init() {
	proto.RegisterType((*GetWorldInfoOut)(nil), "dfproto.GetWorldInfoOut")
	proto.RegisterType((*ListEnumsOut)(nil), "dfproto.ListEnumsOut")
	proto.RegisterType((*ListJobSkillsOut)(nil), "dfproto.ListJobSkillsOut")
	proto.RegisterType((*ListMaterialsIn)(nil), "dfproto.ListMaterialsIn")
	proto.RegisterType((*ListMaterialsOut)(nil), "dfproto.ListMaterialsOut")
	proto.RegisterType((*ListUnitsIn)(nil), "dfproto.ListUnitsIn")
	proto.RegisterType((*ListUnitsOut)(nil), "dfproto.ListUnitsOut")
	proto.RegisterType((*ListSquadsIn)(nil), "dfproto.ListSquadsIn")
	proto.RegisterType((*ListSquadsOut)(nil), "dfproto.ListSquadsOut")
	proto.RegisterType((*SetUnitLaborsIn)(nil), "dfproto.SetUnitLaborsIn")
	proto.RegisterEnum("dfproto.GetWorldInfoOut_Mode", GetWorldInfoOut_Mode_name, GetWorldInfoOut_Mode_value)
}

func init() { proto.RegisterFile("BasicApi.proto", fileDescriptor_BasicApi_38d5d50881d2f891) }

var fileDescriptor_BasicApi_38d5d50881d2f891 = []byte{
	// 909 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x95, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xc7, 0xe1, 0x0f, 0xd9, 0xf2, 0x71, 0xea, 0x38, 0xdc, 0x92, 0x68, 0xc5, 0x36, 0x18, 0xc6,
	0x2e, 0x8c, 0xad, 0xf3, 0x6a, 0x75, 0x1f, 0x37, 0x41, 0x37, 0x07, 0x76, 0x5b, 0x0f, 0x49, 0x3a,
	0xd0, 0xcd, 0x7a, 0x29, 0x30, 0x22, 0xed, 0xb0, 0x95, 0x29, 0x4f, 0xa4, 0x3d, 0xec, 0x55, 0xf6,
	0x00, 0x7b, 0x87, 0xbd, 0xca, 0x1e, 0x60, 0xcf, 0x31, 0x1c, 0x52, 0x56, 0xe2, 0xac, 0x31, 0x72,
	0xa7, 0xc3, 0xf3, 0xfb, 0x1f, 0x8a, 0xff, 0x43, 0x1d, 0x41, 0xeb, 0x94, 0x69, 0x19, 0x0f, 0x97,
	0xb2, 0xbf, 0xcc, 0x52, 0x93, 0x92, 0x3a, 0x9f, 0xd9, 0x87, 0xc7, 0x4d, 0x9b, 0x70, 0xab, 0xdd,
	0xbf, 0x2b, 0xb0, 0xff, 0x52, 0x98, 0xb7, 0x69, 0x96, 0xf0, 0x89, 0x9a, 0xa5, 0xaf, 0x57, 0x86,
	0x0c, 0xa0, 0xba, 0x48, 0xb9, 0x08, 0x4a, 0x9d, 0x72, 0xaf, 0x15, 0x7e, 0xd6, 0xcf, 0x85, 0xfd,
	0x3b, 0x5c, 0xff, 0x3c, 0xe5, 0x82, 0x5a, 0x94, 0x7c, 0x02, 0xbe, 0x66, 0x6b, 0x11, 0x71, 0x99,
	0x05, 0xe5, 0x4e, 0xb9, 0xd7, 0xa0, 0x75, 0x8c, 0x47, 0x32, 0x23, 0x4f, 0x01, 0x7e, 0x47, 0x55,
	0xa4, 0xd8, 0x42, 0x04, 0x95, 0x4e, 0xa9, 0xd7, 0x0c, 0x0f, 0x8a, 0x9a, 0x17, 0x6c, 0x21, 0xb0,
	0x1e, 0x6d, 0x58, 0x08, 0x43, 0x72, 0x08, 0xb5, 0x58, 0xae, 0x23, 0xc9, 0x83, 0x6a, 0xa7, 0xd4,
	0xf3, 0xa8, 0x17, 0xcb, 0xf5, 0x84, 0x93, 0x63, 0xa8, 0x6b, 0x69, 0x04, 0xae, 0x7b, 0x76, 0xbd,
	0x86, 0xe1, 0x84, 0xe3, 0xe6, 0xf3, 0x2c, 0x5d, 0x2d, 0x31, 0x53, 0xb3, 0x99, 0xba, 0x8d, 0x9d,
	0x26, 0x63, 0xb1, 0xd5, 0xd4, 0x9d, 0x06, 0xc3, 0x09, 0x27, 0x5f, 0x40, 0x6b, 0x99, 0xb0, 0x3f,
	0x44, 0x16, 0xad, 0x94, 0x34, 0x98, 0xf7, 0x6d, 0x7e, 0xcf, 0xad, 0x5e, 0x2a, 0x69, 0x26, 0x9c,
	0x7c, 0x09, 0x07, 0x39, 0x75, 0x2d, 0xb5, 0x99, 0xc9, 0x39, 0x82, 0x0d, 0x0b, 0xee, 0xbb, 0xc4,
	0x2b, 0xb7, 0x3e, 0xe1, 0x24, 0x84, 0xc3, 0x38, 0x5d, 0x2c, 0x99, 0x92, 0xa9, 0xba, 0x85, 0xeb,
	0x00, 0x3a, 0x95, 0x9e, 0x47, 0x3f, 0x2a, 0x92, 0x85, 0x44, 0x77, 0x4f, 0xa0, 0x8a, 0x26, 0x92,
	0x16, 0xc0, 0xf9, 0xeb, 0xd1, 0x38, 0x1a, 0xbd, 0x1d, 0xd2, 0x17, 0xed, 0x12, 0x21, 0xd0, 0xb2,
	0xf1, 0x70, 0xf4, 0xeb, 0xf8, 0xe2, 0xcd, 0x25, 0x1d, 0xb7, 0xcb, 0xa4, 0x0d, 0x7b, 0x76, 0xed,
	0x6c, 0xfc, 0x72, 0x7c, 0x31, 0x9a, 0xb6, 0x2b, 0xdd, 0x3f, 0x3d, 0xd8, 0x3b, 0x93, 0xda, 0x8c,
	0xd5, 0x6a, 0xa1, 0xb1, 0x71, 0x27, 0xd0, 0x5a, 0x30, 0x23, 0x32, 0xc9, 0x92, 0x68, 0x96, 0xb0,
	0xb9, 0x0e, 0x4a, 0x9d, 0x4a, 0xaf, 0x19, 0x1e, 0x16, 0x76, 0x23, 0x3a, 0x31, 0x62, 0x81, 0x3e,
	0xd3, 0x47, 0x1b, 0xf8, 0x05, 0xb2, 0xe4, 0x39, 0xec, 0x4b, 0x95, 0x66, 0x73, 0xa6, 0x64, 0x9c,
	0xcb, 0xcb, 0xbb, 0xe4, 0xad, 0x82, 0x76, 0xfa, 0xef, 0xa1, 0x69, 0xbd, 0xb4, 0xd2, 0x41, 0x50,
	0xd9, 0xa5, 0x05, 0x24, 0xad, 0x6c, 0xb0, 0xad, 0x0b, 0x83, 0xea, 0xc3, 0x74, 0xe1, 0xb6, 0xee,
	0x59, 0xe0, 0x3d, 0x4c, 0xf7, 0x8c, 0x7c, 0x0b, 0x36, 0x8a, 0x12, 0x76, 0x95, 0x66, 0x41, 0x6d,
	0x97, 0xac, 0x81, 0xe0, 0x19, 0x72, 0x24, 0x84, 0xc6, 0xbb, 0xf4, 0x2a, 0xd2, 0xef, 0x65, 0x92,
	0x04, 0xf5, 0x5d, 0x22, 0xff, 0x5d, 0x7a, 0x35, 0x45, 0x8c, 0xfc, 0x04, 0x07, 0xb1, 0x14, 0x11,
	0xe3, 0x3c, 0x32, 0x6c, 0x1e, 0x2d, 0x98, 0x7e, 0x3f, 0x08, 0xfc, 0x9d, 0x9e, 0xc6, 0x52, 0x0c,
	0x39, 0x7f, 0xc3, 0xe6, 0xe7, 0x08, 0x7f, 0xa8, 0x42, 0x18, 0x34, 0x1e, 0x5e, 0x21, 0x24, 0x3f,
	0x42, 0x9b, 0x0b, 0x66, 0xae, 0x23, 0xa9, 0x66, 0x69, 0xde, 0x56, 0xd8, 0x59, 0xc0, 0xe2, 0xf8,
	0x4d, 0xba, 0xb6, 0x7e, 0x07, 0xb0, 0xcc, 0xd2, 0x99, 0xd0, 0x5a, 0xa6, 0x2a, 0x68, 0xee, 0x74,
	0xf9, 0x06, 0xec, 0xfe, 0x55, 0x82, 0x36, 0x5e, 0xce, 0x9f, 0x73, 0x33, 0xec, 0x05, 0xfd, 0x0a,
	0x3c, 0x67, 0xe0, 0xdd, 0x7b, 0xb9, 0xa1, 0x86, 0xc6, 0x64, 0xd4, 0x31, 0xe4, 0x87, 0xad, 0x8d,
	0xdd, 0x55, 0x3c, 0x2e, 0x14, 0xbf, 0x14, 0x29, 0xab, 0xb9, 0x85, 0x92, 0x27, 0xe0, 0xb9, 0xde,
	0xba, 0x2b, 0x78, 0x54, 0x68, 0x2e, 0x37, 0xdd, 0x74, 0xdb, 0x58, 0xa8, 0xfb, 0x6f, 0x09, 0xf6,
	0xf1, 0x45, 0xcf, 0xf3, 0x8f, 0x41, 0x4f, 0x14, 0x09, 0xa1, 0x8a, 0x56, 0x07, 0x25, 0x3b, 0xad,
	0x3e, 0x2f, 0x0a, 0xd8, 0xc9, 0xb9, 0x01, 0xd1, 0x22, 0xf4, 0x98, 0x5a, 0x96, 0x0c, 0xa0, 0x2e,
	0x79, 0x94, 0x48, 0x6d, 0xf2, 0x77, 0x0d, 0xee, 0x91, 0x71, 0x5a, 0x93, 0x1c, 0x77, 0x24, 0x01,
	0xd4, 0xaf, 0x56, 0x32, 0x31, 0x52, 0xd9, 0xb9, 0xe8, 0xd3, 0x4d, 0x48, 0x3e, 0x85, 0x46, 0xf1,
	0x75, 0xd9, 0x29, 0xe8, 0xd3, 0x9b, 0x05, 0xcc, 0xc6, 0x99, 0x60, 0x66, 0x95, 0x09, 0x6d, 0x67,
	0xa1, 0x4f, 0x6f, 0x16, 0xc8, 0x11, 0xd4, 0x96, 0x09, 0x53, 0x46, 0xdb, 0x61, 0xe8, 0xd3, 0x3c,
	0xea, 0x8e, 0x5c, 0x43, 0x8a, 0x73, 0x62, 0x43, 0x9e, 0x82, 0xb7, 0x66, 0xc9, 0x4a, 0xe4, 0x0d,
	0x79, 0x7c, 0xff, 0x49, 0xa9, 0x03, 0xbb, 0xff, 0x94, 0xa0, 0x89, 0x65, 0xd0, 0x4b, 0xb4, 0xaa,
	0xbf, 0x65, 0xd5, 0x9d, 0x02, 0x76, 0x8c, 0x6e, 0xdb, 0x74, 0xbc, 0x6d, 0x93, 0x57, 0x98, 0x81,
	0xbf, 0x90, 0x98, 0xa9, 0x88, 0x25, 0x49, 0x7e, 0xa6, 0x3a, 0xc6, 0xc3, 0x24, 0x21, 0x04, 0xaa,
	0x38, 0xb6, 0xad, 0x49, 0x1e, 0xb5, 0xcf, 0xf7, 0xfd, 0x24, 0x08, 0x54, 0xb9, 0x60, 0x3c, 0x3f,
	0xba, 0x7d, 0x26, 0x1f, 0x83, 0xc7, 0x12, 0xb9, 0x16, 0xf6, 0x17, 0xe0, 0x53, 0x17, 0x20, 0xa9,
	0x99, 0x12, 0x76, 0xee, 0xfb, 0xd4, 0x3e, 0x77, 0x4f, 0xdc, 0x40, 0xb5, 0x67, 0x43, 0x7b, 0x9e,
	0x6c, 0xdb, 0x73, 0xf4, 0xe1, 0xd3, 0x6d, 0xac, 0x69, 0x39, 0xf5, 0xf4, 0xb7, 0x15, 0xe3, 0x7a,
	0xa2, 0xba, 0xcf, 0xe1, 0xd1, 0x4d, 0x8c, 0xe5, 0xbe, 0xde, 0x2e, 0x77, 0xbc, 0x5d, 0xce, 0x72,
	0xb7, 0xeb, 0x9d, 0xc2, 0xfe, 0x54, 0x98, 0xe2, 0xd2, 0xa2, 0xdb, 0xdf, 0x40, 0x2d, 0xbe, 0x66,
	0x6a, 0xfe, 0xff, 0x12, 0x05, 0x36, 0x35, 0xcc, 0x08, 0x9a, 0x63, 0xa7, 0xe5, 0x57, 0x95, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x37, 0x96, 0x02, 0x9d, 0x0a, 0x08, 0x00, 0x00,
}
