// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Basic.proto

package dfproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BasicMaterialInfoMask_StateType int32

const (
	BasicMaterialInfoMask_Solid   BasicMaterialInfoMask_StateType = 0
	BasicMaterialInfoMask_Liquid  BasicMaterialInfoMask_StateType = 1
	BasicMaterialInfoMask_Gas     BasicMaterialInfoMask_StateType = 2
	BasicMaterialInfoMask_Powder  BasicMaterialInfoMask_StateType = 3
	BasicMaterialInfoMask_Paste   BasicMaterialInfoMask_StateType = 4
	BasicMaterialInfoMask_Pressed BasicMaterialInfoMask_StateType = 5
)

var BasicMaterialInfoMask_StateType_name = map[int32]string{
	0: "Solid",
	1: "Liquid",
	2: "Gas",
	3: "Powder",
	4: "Paste",
	5: "Pressed",
}
var BasicMaterialInfoMask_StateType_value = map[string]int32{
	"Solid":   0,
	"Liquid":  1,
	"Gas":     2,
	"Powder":  3,
	"Paste":   4,
	"Pressed": 5,
}

func (x BasicMaterialInfoMask_StateType) Enum() *BasicMaterialInfoMask_StateType {
	p := new(BasicMaterialInfoMask_StateType)
	*p = x
	return p
}
func (x BasicMaterialInfoMask_StateType) String() string {
	return proto.EnumName(BasicMaterialInfoMask_StateType_name, int32(x))
}
func (x *BasicMaterialInfoMask_StateType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BasicMaterialInfoMask_StateType_value, data, "BasicMaterialInfoMask_StateType")
	if err != nil {
		return err
	}
	*x = BasicMaterialInfoMask_StateType(value)
	return nil
}
func (BasicMaterialInfoMask_StateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{3, 0}
}

type EnumItemName struct {
	Value *int32  `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	Name  *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// For bitfield members
	BitSize              *int32   `protobuf:"varint,3,opt,name=bit_size,json=bitSize,def=1" json:"bit_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumItemName) Reset()         { *m = EnumItemName{} }
func (m *EnumItemName) String() string { return proto.CompactTextString(m) }
func (*EnumItemName) ProtoMessage()    {}
func (*EnumItemName) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{0}
}
func (m *EnumItemName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumItemName.Unmarshal(m, b)
}
func (m *EnumItemName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumItemName.Marshal(b, m, deterministic)
}
func (dst *EnumItemName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumItemName.Merge(dst, src)
}
func (m *EnumItemName) XXX_Size() int {
	return xxx_messageInfo_EnumItemName.Size(m)
}
func (m *EnumItemName) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumItemName.DiscardUnknown(m)
}

var xxx_messageInfo_EnumItemName proto.InternalMessageInfo

const Default_EnumItemName_BitSize int32 = 1

func (m *EnumItemName) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *EnumItemName) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *EnumItemName) GetBitSize() int32 {
	if m != nil && m.BitSize != nil {
		return *m.BitSize
	}
	return Default_EnumItemName_BitSize
}

type BasicMaterialId struct {
	Type                 *int32   `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Index                *int32   `protobuf:"zigzag32,2,req,name=index" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicMaterialId) Reset()         { *m = BasicMaterialId{} }
func (m *BasicMaterialId) String() string { return proto.CompactTextString(m) }
func (*BasicMaterialId) ProtoMessage()    {}
func (*BasicMaterialId) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{1}
}
func (m *BasicMaterialId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicMaterialId.Unmarshal(m, b)
}
func (m *BasicMaterialId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicMaterialId.Marshal(b, m, deterministic)
}
func (dst *BasicMaterialId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicMaterialId.Merge(dst, src)
}
func (m *BasicMaterialId) XXX_Size() int {
	return xxx_messageInfo_BasicMaterialId.Size(m)
}
func (m *BasicMaterialId) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicMaterialId.DiscardUnknown(m)
}

var xxx_messageInfo_BasicMaterialId proto.InternalMessageInfo

func (m *BasicMaterialId) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *BasicMaterialId) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

type BasicMaterialInfo struct {
	Type  *int32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Index *int32 `protobuf:"zigzag32,2,req,name=index" json:"index,omitempty"`
	// The raw token
	Token *string `protobuf:"bytes,3,req,name=token" json:"token,omitempty"`
	// IF mask.flags:
	// List of material_flags indices
	Flags []int32 `protobuf:"varint,4,rep,name=flags" json:"flags,omitempty"`
	// Material type/index expanded:
	Subtype    *int32  `protobuf:"varint,5,opt,name=subtype,def=-1" json:"subtype,omitempty"`
	CreatureId *int32  `protobuf:"varint,6,opt,name=creature_id,json=creatureId,def=-1" json:"creature_id,omitempty"`
	PlantId    *int32  `protobuf:"varint,7,opt,name=plant_id,json=plantId,def=-1" json:"plant_id,omitempty"`
	HistfigId  *int32  `protobuf:"varint,8,opt,name=histfig_id,json=histfigId,def=-1" json:"histfig_id,omitempty"`
	NamePrefix *string `protobuf:"bytes,9,opt,name=name_prefix,json=namePrefix,def=" json:"name_prefix,omitempty"`
	// IF mask.states: in listed order;
	// ELSE: one state matching mask.temperature
	StateColor      []uint32                     `protobuf:"fixed32,10,rep,name=state_color,json=stateColor" json:"state_color,omitempty"`
	StateName       []string                     `protobuf:"bytes,11,rep,name=state_name,json=stateName" json:"state_name,omitempty"`
	StateAdj        []string                     `protobuf:"bytes,12,rep,name=state_adj,json=stateAdj" json:"state_adj,omitempty"`
	ReactionClass   []string                     `protobuf:"bytes,13,rep,name=reaction_class,json=reactionClass" json:"reaction_class,omitempty"`
	ReactionProduct []*BasicMaterialInfo_Product `protobuf:"bytes,14,rep,name=reaction_product,json=reactionProduct" json:"reaction_product,omitempty"`
	// IF mask.flags:
	InorganicFlags       []int32  `protobuf:"varint,15,rep,name=inorganic_flags,json=inorganicFlags" json:"inorganic_flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicMaterialInfo) Reset()         { *m = BasicMaterialInfo{} }
func (m *BasicMaterialInfo) String() string { return proto.CompactTextString(m) }
func (*BasicMaterialInfo) ProtoMessage()    {}
func (*BasicMaterialInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{2}
}
func (m *BasicMaterialInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicMaterialInfo.Unmarshal(m, b)
}
func (m *BasicMaterialInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicMaterialInfo.Marshal(b, m, deterministic)
}
func (dst *BasicMaterialInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicMaterialInfo.Merge(dst, src)
}
func (m *BasicMaterialInfo) XXX_Size() int {
	return xxx_messageInfo_BasicMaterialInfo.Size(m)
}
func (m *BasicMaterialInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicMaterialInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BasicMaterialInfo proto.InternalMessageInfo

const Default_BasicMaterialInfo_Subtype int32 = -1
const Default_BasicMaterialInfo_CreatureId int32 = -1
const Default_BasicMaterialInfo_PlantId int32 = -1
const Default_BasicMaterialInfo_HistfigId int32 = -1

func (m *BasicMaterialInfo) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *BasicMaterialInfo) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *BasicMaterialInfo) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *BasicMaterialInfo) GetFlags() []int32 {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *BasicMaterialInfo) GetSubtype() int32 {
	if m != nil && m.Subtype != nil {
		return *m.Subtype
	}
	return Default_BasicMaterialInfo_Subtype
}

func (m *BasicMaterialInfo) GetCreatureId() int32 {
	if m != nil && m.CreatureId != nil {
		return *m.CreatureId
	}
	return Default_BasicMaterialInfo_CreatureId
}

func (m *BasicMaterialInfo) GetPlantId() int32 {
	if m != nil && m.PlantId != nil {
		return *m.PlantId
	}
	return Default_BasicMaterialInfo_PlantId
}

func (m *BasicMaterialInfo) GetHistfigId() int32 {
	if m != nil && m.HistfigId != nil {
		return *m.HistfigId
	}
	return Default_BasicMaterialInfo_HistfigId
}

func (m *BasicMaterialInfo) GetNamePrefix() string {
	if m != nil && m.NamePrefix != nil {
		return *m.NamePrefix
	}
	return ""
}

func (m *BasicMaterialInfo) GetStateColor() []uint32 {
	if m != nil {
		return m.StateColor
	}
	return nil
}

func (m *BasicMaterialInfo) GetStateName() []string {
	if m != nil {
		return m.StateName
	}
	return nil
}

func (m *BasicMaterialInfo) GetStateAdj() []string {
	if m != nil {
		return m.StateAdj
	}
	return nil
}

func (m *BasicMaterialInfo) GetReactionClass() []string {
	if m != nil {
		return m.ReactionClass
	}
	return nil
}

func (m *BasicMaterialInfo) GetReactionProduct() []*BasicMaterialInfo_Product {
	if m != nil {
		return m.ReactionProduct
	}
	return nil
}

func (m *BasicMaterialInfo) GetInorganicFlags() []int32 {
	if m != nil {
		return m.InorganicFlags
	}
	return nil
}

// IF mask.reaction:
type BasicMaterialInfo_Product struct {
	Id                   *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Type                 *int32   `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Index                *int32   `protobuf:"zigzag32,3,req,name=index" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicMaterialInfo_Product) Reset()         { *m = BasicMaterialInfo_Product{} }
func (m *BasicMaterialInfo_Product) String() string { return proto.CompactTextString(m) }
func (*BasicMaterialInfo_Product) ProtoMessage()    {}
func (*BasicMaterialInfo_Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{2, 0}
}
func (m *BasicMaterialInfo_Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicMaterialInfo_Product.Unmarshal(m, b)
}
func (m *BasicMaterialInfo_Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicMaterialInfo_Product.Marshal(b, m, deterministic)
}
func (dst *BasicMaterialInfo_Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicMaterialInfo_Product.Merge(dst, src)
}
func (m *BasicMaterialInfo_Product) XXX_Size() int {
	return xxx_messageInfo_BasicMaterialInfo_Product.Size(m)
}
func (m *BasicMaterialInfo_Product) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicMaterialInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_BasicMaterialInfo_Product proto.InternalMessageInfo

func (m *BasicMaterialInfo_Product) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *BasicMaterialInfo_Product) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *BasicMaterialInfo_Product) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

type BasicMaterialInfoMask struct {
	States               []BasicMaterialInfoMask_StateType `protobuf:"varint,1,rep,name=states,enum=dfproto.BasicMaterialInfoMask_StateType" json:"states,omitempty"`
	Temperature          *int32                            `protobuf:"varint,4,opt,name=temperature,def=10015" json:"temperature,omitempty"`
	Flags                *bool                             `protobuf:"varint,2,opt,name=flags,def=0" json:"flags,omitempty"`
	Reaction             *bool                             `protobuf:"varint,3,opt,name=reaction,def=0" json:"reaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *BasicMaterialInfoMask) Reset()         { *m = BasicMaterialInfoMask{} }
func (m *BasicMaterialInfoMask) String() string { return proto.CompactTextString(m) }
func (*BasicMaterialInfoMask) ProtoMessage()    {}
func (*BasicMaterialInfoMask) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{3}
}
func (m *BasicMaterialInfoMask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicMaterialInfoMask.Unmarshal(m, b)
}
func (m *BasicMaterialInfoMask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicMaterialInfoMask.Marshal(b, m, deterministic)
}
func (dst *BasicMaterialInfoMask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicMaterialInfoMask.Merge(dst, src)
}
func (m *BasicMaterialInfoMask) XXX_Size() int {
	return xxx_messageInfo_BasicMaterialInfoMask.Size(m)
}
func (m *BasicMaterialInfoMask) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicMaterialInfoMask.DiscardUnknown(m)
}

var xxx_messageInfo_BasicMaterialInfoMask proto.InternalMessageInfo

const Default_BasicMaterialInfoMask_Temperature int32 = 10015
const Default_BasicMaterialInfoMask_Flags bool = false
const Default_BasicMaterialInfoMask_Reaction bool = false

func (m *BasicMaterialInfoMask) GetStates() []BasicMaterialInfoMask_StateType {
	if m != nil {
		return m.States
	}
	return nil
}

func (m *BasicMaterialInfoMask) GetTemperature() int32 {
	if m != nil && m.Temperature != nil {
		return *m.Temperature
	}
	return Default_BasicMaterialInfoMask_Temperature
}

func (m *BasicMaterialInfoMask) GetFlags() bool {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return Default_BasicMaterialInfoMask_Flags
}

func (m *BasicMaterialInfoMask) GetReaction() bool {
	if m != nil && m.Reaction != nil {
		return *m.Reaction
	}
	return Default_BasicMaterialInfoMask_Reaction
}

type JobSkillAttr struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Key                  *string  `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Caption              *string  `protobuf:"bytes,3,opt,name=caption" json:"caption,omitempty"`
	CaptionNoun          *string  `protobuf:"bytes,4,opt,name=caption_noun,json=captionNoun" json:"caption_noun,omitempty"`
	Profession           *int32   `protobuf:"varint,5,opt,name=profession" json:"profession,omitempty"`
	Labor                *int32   `protobuf:"varint,6,opt,name=labor" json:"labor,omitempty"`
	Type                 *string  `protobuf:"bytes,7,opt,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobSkillAttr) Reset()         { *m = JobSkillAttr{} }
func (m *JobSkillAttr) String() string { return proto.CompactTextString(m) }
func (*JobSkillAttr) ProtoMessage()    {}
func (*JobSkillAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{4}
}
func (m *JobSkillAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobSkillAttr.Unmarshal(m, b)
}
func (m *JobSkillAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobSkillAttr.Marshal(b, m, deterministic)
}
func (dst *JobSkillAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobSkillAttr.Merge(dst, src)
}
func (m *JobSkillAttr) XXX_Size() int {
	return xxx_messageInfo_JobSkillAttr.Size(m)
}
func (m *JobSkillAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_JobSkillAttr.DiscardUnknown(m)
}

var xxx_messageInfo_JobSkillAttr proto.InternalMessageInfo

func (m *JobSkillAttr) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *JobSkillAttr) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *JobSkillAttr) GetCaption() string {
	if m != nil && m.Caption != nil {
		return *m.Caption
	}
	return ""
}

func (m *JobSkillAttr) GetCaptionNoun() string {
	if m != nil && m.CaptionNoun != nil {
		return *m.CaptionNoun
	}
	return ""
}

func (m *JobSkillAttr) GetProfession() int32 {
	if m != nil && m.Profession != nil {
		return *m.Profession
	}
	return 0
}

func (m *JobSkillAttr) GetLabor() int32 {
	if m != nil && m.Labor != nil {
		return *m.Labor
	}
	return 0
}

func (m *JobSkillAttr) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

type ProfessionAttr struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Key                  *string  `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Caption              *string  `protobuf:"bytes,3,opt,name=caption" json:"caption,omitempty"`
	Military             *bool    `protobuf:"varint,4,opt,name=military" json:"military,omitempty"`
	CanAssignLabor       *bool    `protobuf:"varint,5,opt,name=can_assign_labor,json=canAssignLabor" json:"can_assign_labor,omitempty"`
	Parent               *int32   `protobuf:"varint,6,opt,name=parent" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfessionAttr) Reset()         { *m = ProfessionAttr{} }
func (m *ProfessionAttr) String() string { return proto.CompactTextString(m) }
func (*ProfessionAttr) ProtoMessage()    {}
func (*ProfessionAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{5}
}
func (m *ProfessionAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfessionAttr.Unmarshal(m, b)
}
func (m *ProfessionAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfessionAttr.Marshal(b, m, deterministic)
}
func (dst *ProfessionAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfessionAttr.Merge(dst, src)
}
func (m *ProfessionAttr) XXX_Size() int {
	return xxx_messageInfo_ProfessionAttr.Size(m)
}
func (m *ProfessionAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfessionAttr.DiscardUnknown(m)
}

var xxx_messageInfo_ProfessionAttr proto.InternalMessageInfo

func (m *ProfessionAttr) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProfessionAttr) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ProfessionAttr) GetCaption() string {
	if m != nil && m.Caption != nil {
		return *m.Caption
	}
	return ""
}

func (m *ProfessionAttr) GetMilitary() bool {
	if m != nil && m.Military != nil {
		return *m.Military
	}
	return false
}

func (m *ProfessionAttr) GetCanAssignLabor() bool {
	if m != nil && m.CanAssignLabor != nil {
		return *m.CanAssignLabor
	}
	return false
}

func (m *ProfessionAttr) GetParent() int32 {
	if m != nil && m.Parent != nil {
		return *m.Parent
	}
	return 0
}

type UnitLaborAttr struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Key                  *string  `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Caption              *string  `protobuf:"bytes,3,opt,name=caption" json:"caption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitLaborAttr) Reset()         { *m = UnitLaborAttr{} }
func (m *UnitLaborAttr) String() string { return proto.CompactTextString(m) }
func (*UnitLaborAttr) ProtoMessage()    {}
func (*UnitLaborAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{6}
}
func (m *UnitLaborAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitLaborAttr.Unmarshal(m, b)
}
func (m *UnitLaborAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitLaborAttr.Marshal(b, m, deterministic)
}
func (dst *UnitLaborAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitLaborAttr.Merge(dst, src)
}
func (m *UnitLaborAttr) XXX_Size() int {
	return xxx_messageInfo_UnitLaborAttr.Size(m)
}
func (m *UnitLaborAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitLaborAttr.DiscardUnknown(m)
}

var xxx_messageInfo_UnitLaborAttr proto.InternalMessageInfo

func (m *UnitLaborAttr) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *UnitLaborAttr) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *UnitLaborAttr) GetCaption() string {
	if m != nil && m.Caption != nil {
		return *m.Caption
	}
	return ""
}

type NameInfo struct {
	FirstName            *string  `protobuf:"bytes,1,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	Nickname             *string  `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	LanguageId           *int32   `protobuf:"varint,3,opt,name=language_id,json=languageId,def=-1" json:"language_id,omitempty"`
	LastName             *string  `protobuf:"bytes,4,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	EnglishName          *string  `protobuf:"bytes,5,opt,name=english_name,json=englishName" json:"english_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameInfo) Reset()         { *m = NameInfo{} }
func (m *NameInfo) String() string { return proto.CompactTextString(m) }
func (*NameInfo) ProtoMessage()    {}
func (*NameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{7}
}
func (m *NameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameInfo.Unmarshal(m, b)
}
func (m *NameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameInfo.Marshal(b, m, deterministic)
}
func (dst *NameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameInfo.Merge(dst, src)
}
func (m *NameInfo) XXX_Size() int {
	return xxx_messageInfo_NameInfo.Size(m)
}
func (m *NameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NameInfo proto.InternalMessageInfo

const Default_NameInfo_LanguageId int32 = -1

func (m *NameInfo) GetFirstName() string {
	if m != nil && m.FirstName != nil {
		return *m.FirstName
	}
	return ""
}

func (m *NameInfo) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *NameInfo) GetLanguageId() int32 {
	if m != nil && m.LanguageId != nil {
		return *m.LanguageId
	}
	return Default_NameInfo_LanguageId
}

func (m *NameInfo) GetLastName() string {
	if m != nil && m.LastName != nil {
		return *m.LastName
	}
	return ""
}

func (m *NameInfo) GetEnglishName() string {
	if m != nil && m.EnglishName != nil {
		return *m.EnglishName
	}
	return ""
}

type NameTriple struct {
	Normal               *string  `protobuf:"bytes,1,req,name=normal" json:"normal,omitempty"`
	Plural               *string  `protobuf:"bytes,2,opt,name=plural" json:"plural,omitempty"`
	Adjective            *string  `protobuf:"bytes,3,opt,name=adjective" json:"adjective,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameTriple) Reset()         { *m = NameTriple{} }
func (m *NameTriple) String() string { return proto.CompactTextString(m) }
func (*NameTriple) ProtoMessage()    {}
func (*NameTriple) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{8}
}
func (m *NameTriple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameTriple.Unmarshal(m, b)
}
func (m *NameTriple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameTriple.Marshal(b, m, deterministic)
}
func (dst *NameTriple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameTriple.Merge(dst, src)
}
func (m *NameTriple) XXX_Size() int {
	return xxx_messageInfo_NameTriple.Size(m)
}
func (m *NameTriple) XXX_DiscardUnknown() {
	xxx_messageInfo_NameTriple.DiscardUnknown(m)
}

var xxx_messageInfo_NameTriple proto.InternalMessageInfo

func (m *NameTriple) GetNormal() string {
	if m != nil && m.Normal != nil {
		return *m.Normal
	}
	return ""
}

func (m *NameTriple) GetPlural() string {
	if m != nil && m.Plural != nil {
		return *m.Plural
	}
	return ""
}

func (m *NameTriple) GetAdjective() string {
	if m != nil && m.Adjective != nil {
		return *m.Adjective
	}
	return ""
}

type UnitCurseInfo struct {
	AddTags1             *uint32     `protobuf:"fixed32,1,req,name=add_tags1,json=addTags1" json:"add_tags1,omitempty"`
	RemTags1             *uint32     `protobuf:"fixed32,2,req,name=rem_tags1,json=remTags1" json:"rem_tags1,omitempty"`
	AddTags2             *uint32     `protobuf:"fixed32,3,req,name=add_tags2,json=addTags2" json:"add_tags2,omitempty"`
	RemTags2             *uint32     `protobuf:"fixed32,4,req,name=rem_tags2,json=remTags2" json:"rem_tags2,omitempty"`
	Name                 *NameTriple `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UnitCurseInfo) Reset()         { *m = UnitCurseInfo{} }
func (m *UnitCurseInfo) String() string { return proto.CompactTextString(m) }
func (*UnitCurseInfo) ProtoMessage()    {}
func (*UnitCurseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{9}
}
func (m *UnitCurseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitCurseInfo.Unmarshal(m, b)
}
func (m *UnitCurseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitCurseInfo.Marshal(b, m, deterministic)
}
func (dst *UnitCurseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitCurseInfo.Merge(dst, src)
}
func (m *UnitCurseInfo) XXX_Size() int {
	return xxx_messageInfo_UnitCurseInfo.Size(m)
}
func (m *UnitCurseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitCurseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UnitCurseInfo proto.InternalMessageInfo

func (m *UnitCurseInfo) GetAddTags1() uint32 {
	if m != nil && m.AddTags1 != nil {
		return *m.AddTags1
	}
	return 0
}

func (m *UnitCurseInfo) GetRemTags1() uint32 {
	if m != nil && m.RemTags1 != nil {
		return *m.RemTags1
	}
	return 0
}

func (m *UnitCurseInfo) GetAddTags2() uint32 {
	if m != nil && m.AddTags2 != nil {
		return *m.AddTags2
	}
	return 0
}

func (m *UnitCurseInfo) GetRemTags2() uint32 {
	if m != nil && m.RemTags2 != nil {
		return *m.RemTags2
	}
	return 0
}

func (m *UnitCurseInfo) GetName() *NameTriple {
	if m != nil {
		return m.Name
	}
	return nil
}

type SkillInfo struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Level                *int32   `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	Experience           *int32   `protobuf:"varint,3,req,name=experience" json:"experience,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillInfo) Reset()         { *m = SkillInfo{} }
func (m *SkillInfo) String() string { return proto.CompactTextString(m) }
func (*SkillInfo) ProtoMessage()    {}
func (*SkillInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{10}
}
func (m *SkillInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillInfo.Unmarshal(m, b)
}
func (m *SkillInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillInfo.Marshal(b, m, deterministic)
}
func (dst *SkillInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillInfo.Merge(dst, src)
}
func (m *SkillInfo) XXX_Size() int {
	return xxx_messageInfo_SkillInfo.Size(m)
}
func (m *SkillInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SkillInfo proto.InternalMessageInfo

func (m *SkillInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SkillInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *SkillInfo) GetExperience() int32 {
	if m != nil && m.Experience != nil {
		return *m.Experience
	}
	return 0
}

type UnitMiscTrait struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Value                *int32   `protobuf:"varint,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitMiscTrait) Reset()         { *m = UnitMiscTrait{} }
func (m *UnitMiscTrait) String() string { return proto.CompactTextString(m) }
func (*UnitMiscTrait) ProtoMessage()    {}
func (*UnitMiscTrait) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{11}
}
func (m *UnitMiscTrait) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitMiscTrait.Unmarshal(m, b)
}
func (m *UnitMiscTrait) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitMiscTrait.Marshal(b, m, deterministic)
}
func (dst *UnitMiscTrait) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitMiscTrait.Merge(dst, src)
}
func (m *UnitMiscTrait) XXX_Size() int {
	return xxx_messageInfo_UnitMiscTrait.Size(m)
}
func (m *UnitMiscTrait) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitMiscTrait.DiscardUnknown(m)
}

var xxx_messageInfo_UnitMiscTrait proto.InternalMessageInfo

func (m *UnitMiscTrait) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *UnitMiscTrait) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type BasicUnitInfo struct {
	UnitId     *int32    `protobuf:"varint,1,req,name=unit_id,json=unitId" json:"unit_id,omitempty"`
	PosX       *int32    `protobuf:"varint,13,req,name=pos_x,json=posX" json:"pos_x,omitempty"`
	PosY       *int32    `protobuf:"varint,14,req,name=pos_y,json=posY" json:"pos_y,omitempty"`
	PosZ       *int32    `protobuf:"varint,15,req,name=pos_z,json=posZ" json:"pos_z,omitempty"`
	Name       *NameInfo `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Flags1     *uint32   `protobuf:"fixed32,3,req,name=flags1" json:"flags1,omitempty"`
	Flags2     *uint32   `protobuf:"fixed32,4,req,name=flags2" json:"flags2,omitempty"`
	Flags3     *uint32   `protobuf:"fixed32,5,req,name=flags3" json:"flags3,omitempty"`
	Race       *int32    `protobuf:"varint,6,req,name=race" json:"race,omitempty"`
	Caste      *int32    `protobuf:"varint,7,req,name=caste" json:"caste,omitempty"`
	Gender     *int32    `protobuf:"varint,8,opt,name=gender,def=-1" json:"gender,omitempty"`
	CivId      *int32    `protobuf:"varint,9,opt,name=civ_id,json=civId,def=-1" json:"civ_id,omitempty"`
	HistfigId  *int32    `protobuf:"varint,10,opt,name=histfig_id,json=histfigId,def=-1" json:"histfig_id,omitempty"`
	DeathId    *int32    `protobuf:"varint,17,opt,name=death_id,json=deathId,def=-1" json:"death_id,omitempty"`
	DeathFlags *uint32   `protobuf:"varint,18,opt,name=death_flags,json=deathFlags" json:"death_flags,omitempty"`
	// IF mask.profession:
	SquadId          *int32  `protobuf:"varint,19,opt,name=squad_id,json=squadId,def=-1" json:"squad_id,omitempty"`
	SquadPosition    *int32  `protobuf:"varint,20,opt,name=squad_position,json=squadPosition,def=-1" json:"squad_position,omitempty"`
	Profession       *int32  `protobuf:"varint,22,opt,name=profession,def=-1" json:"profession,omitempty"`
	CustomProfession *string `protobuf:"bytes,23,opt,name=custom_profession,json=customProfession" json:"custom_profession,omitempty"`
	// IF mask.labors:
	Labors []int32 `protobuf:"varint,11,rep,name=labors" json:"labors,omitempty"`
	// IF mask.skills:
	Skills []*SkillInfo `protobuf:"bytes,12,rep,name=skills" json:"skills,omitempty"`
	// IF mask.misc_traits:
	MiscTraits           []*UnitMiscTrait `protobuf:"bytes,24,rep,name=misc_traits,json=miscTraits" json:"misc_traits,omitempty"`
	Curse                *UnitCurseInfo   `protobuf:"bytes,16,opt,name=curse" json:"curse,omitempty"`
	Burrows              []int32          `protobuf:"varint,21,rep,name=burrows" json:"burrows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BasicUnitInfo) Reset()         { *m = BasicUnitInfo{} }
func (m *BasicUnitInfo) String() string { return proto.CompactTextString(m) }
func (*BasicUnitInfo) ProtoMessage()    {}
func (*BasicUnitInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{12}
}
func (m *BasicUnitInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicUnitInfo.Unmarshal(m, b)
}
func (m *BasicUnitInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicUnitInfo.Marshal(b, m, deterministic)
}
func (dst *BasicUnitInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicUnitInfo.Merge(dst, src)
}
func (m *BasicUnitInfo) XXX_Size() int {
	return xxx_messageInfo_BasicUnitInfo.Size(m)
}
func (m *BasicUnitInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicUnitInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BasicUnitInfo proto.InternalMessageInfo

const Default_BasicUnitInfo_Gender int32 = -1
const Default_BasicUnitInfo_CivId int32 = -1
const Default_BasicUnitInfo_HistfigId int32 = -1
const Default_BasicUnitInfo_DeathId int32 = -1
const Default_BasicUnitInfo_SquadId int32 = -1
const Default_BasicUnitInfo_SquadPosition int32 = -1
const Default_BasicUnitInfo_Profession int32 = -1

func (m *BasicUnitInfo) GetUnitId() int32 {
	if m != nil && m.UnitId != nil {
		return *m.UnitId
	}
	return 0
}

func (m *BasicUnitInfo) GetPosX() int32 {
	if m != nil && m.PosX != nil {
		return *m.PosX
	}
	return 0
}

func (m *BasicUnitInfo) GetPosY() int32 {
	if m != nil && m.PosY != nil {
		return *m.PosY
	}
	return 0
}

func (m *BasicUnitInfo) GetPosZ() int32 {
	if m != nil && m.PosZ != nil {
		return *m.PosZ
	}
	return 0
}

func (m *BasicUnitInfo) GetName() *NameInfo {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *BasicUnitInfo) GetFlags1() uint32 {
	if m != nil && m.Flags1 != nil {
		return *m.Flags1
	}
	return 0
}

func (m *BasicUnitInfo) GetFlags2() uint32 {
	if m != nil && m.Flags2 != nil {
		return *m.Flags2
	}
	return 0
}

func (m *BasicUnitInfo) GetFlags3() uint32 {
	if m != nil && m.Flags3 != nil {
		return *m.Flags3
	}
	return 0
}

func (m *BasicUnitInfo) GetRace() int32 {
	if m != nil && m.Race != nil {
		return *m.Race
	}
	return 0
}

func (m *BasicUnitInfo) GetCaste() int32 {
	if m != nil && m.Caste != nil {
		return *m.Caste
	}
	return 0
}

func (m *BasicUnitInfo) GetGender() int32 {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return Default_BasicUnitInfo_Gender
}

func (m *BasicUnitInfo) GetCivId() int32 {
	if m != nil && m.CivId != nil {
		return *m.CivId
	}
	return Default_BasicUnitInfo_CivId
}

func (m *BasicUnitInfo) GetHistfigId() int32 {
	if m != nil && m.HistfigId != nil {
		return *m.HistfigId
	}
	return Default_BasicUnitInfo_HistfigId
}

func (m *BasicUnitInfo) GetDeathId() int32 {
	if m != nil && m.DeathId != nil {
		return *m.DeathId
	}
	return Default_BasicUnitInfo_DeathId
}

func (m *BasicUnitInfo) GetDeathFlags() uint32 {
	if m != nil && m.DeathFlags != nil {
		return *m.DeathFlags
	}
	return 0
}

func (m *BasicUnitInfo) GetSquadId() int32 {
	if m != nil && m.SquadId != nil {
		return *m.SquadId
	}
	return Default_BasicUnitInfo_SquadId
}

func (m *BasicUnitInfo) GetSquadPosition() int32 {
	if m != nil && m.SquadPosition != nil {
		return *m.SquadPosition
	}
	return Default_BasicUnitInfo_SquadPosition
}

func (m *BasicUnitInfo) GetProfession() int32 {
	if m != nil && m.Profession != nil {
		return *m.Profession
	}
	return Default_BasicUnitInfo_Profession
}

func (m *BasicUnitInfo) GetCustomProfession() string {
	if m != nil && m.CustomProfession != nil {
		return *m.CustomProfession
	}
	return ""
}

func (m *BasicUnitInfo) GetLabors() []int32 {
	if m != nil {
		return m.Labors
	}
	return nil
}

func (m *BasicUnitInfo) GetSkills() []*SkillInfo {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *BasicUnitInfo) GetMiscTraits() []*UnitMiscTrait {
	if m != nil {
		return m.MiscTraits
	}
	return nil
}

func (m *BasicUnitInfo) GetCurse() *UnitCurseInfo {
	if m != nil {
		return m.Curse
	}
	return nil
}

func (m *BasicUnitInfo) GetBurrows() []int32 {
	if m != nil {
		return m.Burrows
	}
	return nil
}

type BasicUnitInfoMask struct {
	Labors               *bool    `protobuf:"varint,1,opt,name=labors,def=0" json:"labors,omitempty"`
	Skills               *bool    `protobuf:"varint,2,opt,name=skills,def=0" json:"skills,omitempty"`
	Profession           *bool    `protobuf:"varint,3,opt,name=profession,def=0" json:"profession,omitempty"`
	MiscTraits           *bool    `protobuf:"varint,4,opt,name=misc_traits,json=miscTraits,def=0" json:"misc_traits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicUnitInfoMask) Reset()         { *m = BasicUnitInfoMask{} }
func (m *BasicUnitInfoMask) String() string { return proto.CompactTextString(m) }
func (*BasicUnitInfoMask) ProtoMessage()    {}
func (*BasicUnitInfoMask) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{13}
}
func (m *BasicUnitInfoMask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicUnitInfoMask.Unmarshal(m, b)
}
func (m *BasicUnitInfoMask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicUnitInfoMask.Marshal(b, m, deterministic)
}
func (dst *BasicUnitInfoMask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicUnitInfoMask.Merge(dst, src)
}
func (m *BasicUnitInfoMask) XXX_Size() int {
	return xxx_messageInfo_BasicUnitInfoMask.Size(m)
}
func (m *BasicUnitInfoMask) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicUnitInfoMask.DiscardUnknown(m)
}

var xxx_messageInfo_BasicUnitInfoMask proto.InternalMessageInfo

const Default_BasicUnitInfoMask_Labors bool = false
const Default_BasicUnitInfoMask_Skills bool = false
const Default_BasicUnitInfoMask_Profession bool = false
const Default_BasicUnitInfoMask_MiscTraits bool = false

func (m *BasicUnitInfoMask) GetLabors() bool {
	if m != nil && m.Labors != nil {
		return *m.Labors
	}
	return Default_BasicUnitInfoMask_Labors
}

func (m *BasicUnitInfoMask) GetSkills() bool {
	if m != nil && m.Skills != nil {
		return *m.Skills
	}
	return Default_BasicUnitInfoMask_Skills
}

func (m *BasicUnitInfoMask) GetProfession() bool {
	if m != nil && m.Profession != nil {
		return *m.Profession
	}
	return Default_BasicUnitInfoMask_Profession
}

func (m *BasicUnitInfoMask) GetMiscTraits() bool {
	if m != nil && m.MiscTraits != nil {
		return *m.MiscTraits
	}
	return Default_BasicUnitInfoMask_MiscTraits
}

type BasicSquadInfo struct {
	SquadId *int32    `protobuf:"varint,1,req,name=squad_id,json=squadId" json:"squad_id,omitempty"`
	Name    *NameInfo `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// A special field completely overriding the name:
	Alias *string `protobuf:"bytes,3,opt,name=alias" json:"alias,omitempty"`
	// Member histfig ids:
	Members              []int32  `protobuf:"zigzag32,4,rep,name=members" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicSquadInfo) Reset()         { *m = BasicSquadInfo{} }
func (m *BasicSquadInfo) String() string { return proto.CompactTextString(m) }
func (*BasicSquadInfo) ProtoMessage()    {}
func (*BasicSquadInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{14}
}
func (m *BasicSquadInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicSquadInfo.Unmarshal(m, b)
}
func (m *BasicSquadInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicSquadInfo.Marshal(b, m, deterministic)
}
func (dst *BasicSquadInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicSquadInfo.Merge(dst, src)
}
func (m *BasicSquadInfo) XXX_Size() int {
	return xxx_messageInfo_BasicSquadInfo.Size(m)
}
func (m *BasicSquadInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicSquadInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BasicSquadInfo proto.InternalMessageInfo

func (m *BasicSquadInfo) GetSquadId() int32 {
	if m != nil && m.SquadId != nil {
		return *m.SquadId
	}
	return 0
}

func (m *BasicSquadInfo) GetName() *NameInfo {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *BasicSquadInfo) GetAlias() string {
	if m != nil && m.Alias != nil {
		return *m.Alias
	}
	return ""
}

func (m *BasicSquadInfo) GetMembers() []int32 {
	if m != nil {
		return m.Members
	}
	return nil
}

type UnitLaborState struct {
	UnitId               *int32   `protobuf:"varint,1,req,name=unit_id,json=unitId" json:"unit_id,omitempty"`
	Labor                *int32   `protobuf:"varint,2,req,name=labor" json:"labor,omitempty"`
	Value                *bool    `protobuf:"varint,3,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitLaborState) Reset()         { *m = UnitLaborState{} }
func (m *UnitLaborState) String() string { return proto.CompactTextString(m) }
func (*UnitLaborState) ProtoMessage()    {}
func (*UnitLaborState) Descriptor() ([]byte, []int) {
	return fileDescriptor_Basic_d11a354232a44c5d, []int{15}
}
func (m *UnitLaborState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitLaborState.Unmarshal(m, b)
}
func (m *UnitLaborState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitLaborState.Marshal(b, m, deterministic)
}
func (dst *UnitLaborState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitLaborState.Merge(dst, src)
}
func (m *UnitLaborState) XXX_Size() int {
	return xxx_messageInfo_UnitLaborState.Size(m)
}
func (m *UnitLaborState) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitLaborState.DiscardUnknown(m)
}

var xxx_messageInfo_UnitLaborState proto.InternalMessageInfo

func (m *UnitLaborState) GetUnitId() int32 {
	if m != nil && m.UnitId != nil {
		return *m.UnitId
	}
	return 0
}

func (m *UnitLaborState) GetLabor() int32 {
	if m != nil && m.Labor != nil {
		return *m.Labor
	}
	return 0
}

func (m *UnitLaborState) GetValue() bool {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return false
}

func init() {
	proto.RegisterType((*EnumItemName)(nil), "dfproto.EnumItemName")
	proto.RegisterType((*BasicMaterialId)(nil), "dfproto.BasicMaterialId")
	proto.RegisterType((*BasicMaterialInfo)(nil), "dfproto.BasicMaterialInfo")
	proto.RegisterType((*BasicMaterialInfo_Product)(nil), "dfproto.BasicMaterialInfo.Product")
	proto.RegisterType((*BasicMaterialInfoMask)(nil), "dfproto.BasicMaterialInfoMask")
	proto.RegisterType((*JobSkillAttr)(nil), "dfproto.JobSkillAttr")
	proto.RegisterType((*ProfessionAttr)(nil), "dfproto.ProfessionAttr")
	proto.RegisterType((*UnitLaborAttr)(nil), "dfproto.UnitLaborAttr")
	proto.RegisterType((*NameInfo)(nil), "dfproto.NameInfo")
	proto.RegisterType((*NameTriple)(nil), "dfproto.NameTriple")
	proto.RegisterType((*UnitCurseInfo)(nil), "dfproto.UnitCurseInfo")
	proto.RegisterType((*SkillInfo)(nil), "dfproto.SkillInfo")
	proto.RegisterType((*UnitMiscTrait)(nil), "dfproto.UnitMiscTrait")
	proto.RegisterType((*BasicUnitInfo)(nil), "dfproto.BasicUnitInfo")
	proto.RegisterType((*BasicUnitInfoMask)(nil), "dfproto.BasicUnitInfoMask")
	proto.RegisterType((*BasicSquadInfo)(nil), "dfproto.BasicSquadInfo")
	proto.RegisterType((*UnitLaborState)(nil), "dfproto.UnitLaborState")
	proto.RegisterEnum("dfproto.BasicMaterialInfoMask_StateType", BasicMaterialInfoMask_StateType_name, BasicMaterialInfoMask_StateType_value)
}

func init() { proto.RegisterFile("Basic.proto", fileDescriptor_Basic_d11a354232a44c5d) }

var fileDescriptor_Basic_d11a354232a44c5d = []byte{
	// 1425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x6e, 0xdb, 0xc6,
	0x13, 0x8f, 0x24, 0x53, 0x12, 0x47, 0xb6, 0x2c, 0x6f, 0x12, 0x87, 0x71, 0xe2, 0xff, 0x5f, 0x66,
	0x91, 0x46, 0xfd, 0x32, 0x62, 0x05, 0x41, 0x81, 0xf4, 0xd2, 0xc4, 0xe8, 0x87, 0xda, 0x38, 0x75,
	0x69, 0xa7, 0x68, 0x73, 0x11, 0xd6, 0xe4, 0x4a, 0xd9, 0x98, 0x22, 0x95, 0x5d, 0xd2, 0xb1, 0x73,
	0xec, 0x2b, 0xf4, 0x05, 0x7a, 0x2e, 0x7a, 0xef, 0x7b, 0xf4, 0x71, 0x7a, 0x2a, 0x66, 0x96, 0x5c,
	0x51, 0x4d, 0x02, 0x04, 0xc8, 0x89, 0x3b, 0xbf, 0x99, 0x59, 0xce, 0xce, 0xce, 0xfc, 0x66, 0xa1,
	0xf3, 0x90, 0x6b, 0x19, 0xee, 0xce, 0x55, 0x9a, 0xa5, 0xac, 0x15, 0x4d, 0x68, 0xe1, 0xff, 0x04,
	0xab, 0x5f, 0x25, 0xf9, 0x6c, 0x94, 0x89, 0xd9, 0x63, 0x3e, 0x13, 0xec, 0x0a, 0x38, 0x67, 0x3c,
	0xce, 0x85, 0x57, 0xeb, 0xd7, 0x07, 0x4e, 0x60, 0x04, 0xc6, 0x60, 0x25, 0xe1, 0x33, 0xe1, 0xd5,
	0xfb, 0xb5, 0x81, 0x1b, 0xd0, 0x9a, 0xdd, 0x84, 0xf6, 0x89, 0xcc, 0xc6, 0x5a, 0xbe, 0x12, 0x5e,
	0xa3, 0x5f, 0x1b, 0x38, 0xf7, 0x6b, 0x7b, 0x41, 0xeb, 0x44, 0x66, 0x47, 0xf2, 0x95, 0xf0, 0xbf,
	0x80, 0x75, 0xfa, 0xdf, 0x01, 0xcf, 0x84, 0x92, 0x3c, 0x1e, 0x45, 0xb8, 0x49, 0x76, 0x31, 0x2f,
	0x77, 0xa6, 0x35, 0xfe, 0x4e, 0x26, 0x91, 0x38, 0xf7, 0xea, 0xfd, 0xfa, 0x60, 0x23, 0x30, 0x82,
	0xff, 0xf7, 0x0a, 0x6c, 0x2c, 0x7b, 0x27, 0x93, 0xf4, 0xdd, 0xfd, 0x11, 0xcd, 0xd2, 0x53, 0x91,
	0x78, 0x8d, 0x7e, 0x7d, 0xe0, 0x06, 0x46, 0x40, 0x74, 0x12, 0xf3, 0xa9, 0xf6, 0x56, 0xfa, 0x0d,
	0x3c, 0x1a, 0x09, 0xec, 0x26, 0xb4, 0x74, 0x7e, 0x42, 0x1b, 0x3b, 0x74, 0x8a, 0xfa, 0x67, 0x7b,
	0x41, 0x09, 0xb1, 0x0f, 0xa0, 0x13, 0x2a, 0xc1, 0xb3, 0x5c, 0x89, 0xb1, 0x8c, 0xbc, 0xa6, 0xb5,
	0x80, 0x12, 0x1e, 0x45, 0x6c, 0x1b, 0xda, 0xf3, 0x98, 0x27, 0x19, 0x5a, 0xb4, 0x16, 0x7b, 0x10,
	0x36, 0x8a, 0xd8, 0x0e, 0xc0, 0x33, 0xa9, 0xb3, 0x89, 0x9c, 0xa2, 0x41, 0xdb, 0x1a, 0xb8, 0x05,
	0x4a, 0x26, 0x1d, 0xcc, 0xe9, 0x78, 0xae, 0xc4, 0x44, 0x9e, 0x7b, 0x2e, 0xa6, 0xf9, 0xfe, 0xa5,
	0x00, 0x10, 0x3c, 0x24, 0x8c, 0xfd, 0x1f, 0x3a, 0x3a, 0xe3, 0x99, 0x18, 0x87, 0x69, 0x9c, 0x2a,
	0x0f, 0xfa, 0x8d, 0x41, 0x2b, 0x00, 0x82, 0xf6, 0x11, 0x61, 0xdb, 0x60, 0xa4, 0x31, 0xdd, 0x54,
	0xa7, 0xdf, 0x18, 0xb8, 0x81, 0x4b, 0x08, 0x5d, 0xec, 0x0d, 0x30, 0xc2, 0x98, 0x47, 0xcf, 0xbd,
	0x55, 0xd2, 0xb6, 0x09, 0x78, 0x10, 0x3d, 0x67, 0xb7, 0xa0, 0xab, 0x04, 0x0f, 0x33, 0x99, 0x26,
	0xe3, 0x30, 0xe6, 0x5a, 0x7b, 0x6b, 0x64, 0xb1, 0x56, 0xa2, 0xfb, 0x08, 0xb2, 0x03, 0xe8, 0x59,
	0xb3, 0xb9, 0x4a, 0xa3, 0x3c, 0xcc, 0xbc, 0x6e, 0xbf, 0x31, 0xe8, 0x0c, 0xfd, 0xdd, 0xa2, 0xa0,
	0x76, 0x5f, 0xbb, 0xb7, 0xdd, 0x43, 0x63, 0x19, 0xac, 0x97, 0xbe, 0x05, 0xc0, 0x6e, 0xc3, 0xba,
	0x4c, 0x52, 0x35, 0xe5, 0x89, 0x0c, 0xc7, 0xe6, 0x6a, 0xd6, 0xe9, 0x6a, 0xba, 0x16, 0xfe, 0x1a,
	0xd1, 0xad, 0x7d, 0x68, 0x95, 0x3e, 0x5d, 0xa8, 0xcb, 0x88, 0x4a, 0xc0, 0x0d, 0xea, 0x72, 0x51,
	0x54, 0xf5, 0x37, 0x15, 0x45, 0xa3, 0x5a, 0x54, 0xbf, 0xd5, 0xe1, 0xea, 0x6b, 0xc1, 0x1d, 0x70,
	0x7d, 0xca, 0xbe, 0x84, 0x26, 0x65, 0x42, 0x7b, 0xb5, 0x7e, 0x63, 0xd0, 0x1d, 0x0e, 0xde, 0x7e,
	0x18, 0xb4, 0xdf, 0x3d, 0x42, 0xe3, 0xe3, 0x8b, 0xb9, 0x08, 0x0a, 0x3f, 0x76, 0x1b, 0x3a, 0x99,
	0x98, 0xcd, 0x85, 0xa2, 0x92, 0xf0, 0x56, 0xe8, 0x8e, 0x9d, 0xbd, 0x3b, 0x77, 0xf6, 0xee, 0x05,
	0x55, 0x0d, 0xbb, 0x51, 0xd6, 0x20, 0x76, 0x52, 0xfb, 0xbe, 0x33, 0xe1, 0xb1, 0x16, 0x65, 0x29,
	0xee, 0x40, 0xbb, 0x4c, 0x11, 0x75, 0x94, 0xd5, 0x5b, 0xd8, 0xff, 0x01, 0x5c, 0xfb, 0x77, 0xe6,
	0x82, 0x73, 0x94, 0xc6, 0x32, 0xea, 0x5d, 0x62, 0x00, 0xcd, 0x47, 0xf2, 0x45, 0x2e, 0xa3, 0x5e,
	0x8d, 0xb5, 0xa0, 0xf1, 0x0d, 0xd7, 0xbd, 0x3a, 0x82, 0x87, 0xe9, 0xcb, 0x48, 0xa8, 0x5e, 0x03,
	0x6d, 0x0f, 0xb9, 0xce, 0x44, 0x6f, 0x85, 0x75, 0x30, 0x9b, 0x42, 0x6b, 0x11, 0xf5, 0x1c, 0xff,
	0xaf, 0x1a, 0xac, 0x7e, 0x97, 0x9e, 0x1c, 0x9d, 0xca, 0x38, 0x7e, 0x90, 0x65, 0xaa, 0x92, 0x60,
	0x87, 0x12, 0xdc, 0x83, 0xc6, 0xa9, 0xb8, 0xa0, 0xfc, 0xba, 0x01, 0x2e, 0x99, 0x07, 0xad, 0x90,
	0xcf, 0x6d, 0x94, 0x6e, 0x50, 0x8a, 0x6c, 0x07, 0x56, 0x8b, 0xe5, 0x38, 0x49, 0xf3, 0x84, 0xf2,
	0xe0, 0x06, 0x9d, 0x02, 0x7b, 0x9c, 0xe6, 0x09, 0xfb, 0x1f, 0xc0, 0x5c, 0xa5, 0x13, 0xa1, 0x35,
	0xfa, 0x53, 0xc7, 0x05, 0x15, 0x04, 0xef, 0x2e, 0xe6, 0x27, 0xa9, 0x32, 0xad, 0x16, 0x18, 0xc1,
	0xde, 0x72, 0xcb, 0xf0, 0x0f, 0xae, 0xfd, 0x3f, 0x6a, 0xd0, 0x3d, 0xb4, 0x8e, 0xef, 0x1d, 0xfb,
	0x16, 0xb4, 0x67, 0x32, 0x96, 0x19, 0x57, 0x17, 0x14, 0x77, 0x3b, 0xb0, 0x32, 0x1b, 0x40, 0x2f,
	0xe4, 0xc9, 0x98, 0x6b, 0x2d, 0xa7, 0xc9, 0xd8, 0xc4, 0xe7, 0x90, 0x4d, 0x37, 0xe4, 0xc9, 0x03,
	0x82, 0x1f, 0x51, 0xa0, 0x9b, 0xd0, 0x9c, 0x73, 0x25, 0x92, 0xac, 0x88, 0xbf, 0x90, 0xfc, 0xef,
	0x61, 0xed, 0x49, 0x22, 0x33, 0x32, 0x7a, 0xdf, 0x50, 0xf1, 0xe4, 0x6d, 0xec, 0x69, 0x62, 0xc5,
	0x6d, 0x80, 0x89, 0x54, 0x3a, 0x33, 0x6d, 0x5f, 0x23, 0x4b, 0x97, 0x10, 0x6a, 0xfb, 0x2d, 0x68,
	0x27, 0x32, 0x3c, 0xad, 0xb0, 0xb7, 0x95, 0x91, 0xdc, 0x62, 0x9e, 0x4c, 0x73, 0x3e, 0x25, 0x72,
	0x6b, 0x2c, 0xc8, 0xad, 0x84, 0x47, 0x11, 0xf2, 0x46, 0xcc, 0xcb, 0xed, 0xcd, 0x85, 0xb6, 0x11,
	0xa0, 0xdd, 0x77, 0x60, 0x55, 0x24, 0xd3, 0x58, 0xea, 0x67, 0x46, 0xef, 0x98, 0x0b, 0x2f, 0x30,
	0x34, 0xf1, 0x9f, 0x02, 0xe0, 0xf7, 0x58, 0xc9, 0x79, 0x2c, 0x30, 0x3f, 0x49, 0xaa, 0x66, 0x3c,
	0x2e, 0x5a, 0xb8, 0x90, 0x28, 0x6f, 0x71, 0xae, 0x78, 0x5c, 0x04, 0x59, 0x48, 0xec, 0x26, 0xb8,
	0x3c, 0x7a, 0x2e, 0xc2, 0x4c, 0x9e, 0x89, 0x22, 0x0d, 0x0b, 0xc0, 0xff, 0xb3, 0x66, 0xd2, 0xba,
	0x9f, 0x2b, 0x6d, 0xb2, 0x71, 0x03, 0xed, 0xa3, 0x71, 0xc6, 0xa7, 0x7a, 0x8f, 0x7e, 0xd1, 0x0a,
	0xda, 0x3c, 0x8a, 0x8e, 0x51, 0x46, 0xa5, 0x12, 0xb3, 0x42, 0x59, 0x37, 0x4a, 0x25, 0x66, 0x56,
	0x59, 0x7a, 0x0e, 0x89, 0x38, 0x16, 0x9e, 0xc3, 0xaa, 0xe7, 0xd0, 0x5b, 0x59, 0xf2, 0x1c, 0xb2,
	0xdb, 0xc5, 0x70, 0xc4, 0xc3, 0x77, 0x86, 0x97, 0x2d, 0x79, 0x2c, 0x8e, 0x6d, 0x26, 0xa6, 0xff,
	0x23, 0xb8, 0xd4, 0x67, 0x14, 0xe9, 0x7f, 0x0b, 0x00, 0x0b, 0x5f, 0x9c, 0x89, 0xb8, 0x60, 0x32,
	0x23, 0x60, 0xbb, 0x88, 0xf3, 0xb9, 0x50, 0x52, 0x24, 0xa1, 0xa0, 0xb0, 0x9c, 0xa0, 0x82, 0xf8,
	0xf7, 0x4c, 0x02, 0x0e, 0xa4, 0x0e, 0x8f, 0x15, 0x97, 0xd9, 0x9b, 0xb6, 0x35, 0xf3, 0xbc, 0x5e,
	0x99, 0xe7, 0xfe, 0x3f, 0x0e, 0xac, 0x11, 0xb7, 0xa1, 0x33, 0x85, 0x73, 0x0d, 0x5a, 0x79, 0x22,
	0x69, 0x84, 0x19, 0xe7, 0x26, 0x8a, 0xa3, 0x88, 0x5d, 0x06, 0x67, 0x9e, 0xea, 0xf1, 0xb9, 0xb7,
	0x66, 0x18, 0x76, 0x9e, 0xea, 0x9f, 0x4b, 0xf0, 0xc2, 0xeb, 0x5a, 0xf0, 0x97, 0x12, 0x7c, 0xe5,
	0xad, 0x5b, 0xf0, 0x29, 0xbb, 0x55, 0x79, 0x39, 0x74, 0x86, 0x1b, 0x4b, 0xc9, 0xc1, 0x1f, 0x17,
	0x8f, 0x89, 0x4d, 0x68, 0x12, 0x07, 0xee, 0x15, 0xa9, 0x2f, 0x24, 0x8b, 0x97, 0x59, 0x2f, 0x24,
	0x8b, 0xdf, 0xf5, 0x9c, 0x0a, 0x7e, 0x17, 0x89, 0x42, 0xf1, 0x50, 0x78, 0x4d, 0x13, 0x02, 0xae,
	0x31, 0x05, 0x21, 0x52, 0x9f, 0xd7, 0x32, 0x29, 0x20, 0x81, 0x6d, 0x41, 0x73, 0x2a, 0x92, 0x48,
	0xa8, 0xca, 0x44, 0x2e, 0x10, 0x76, 0x1d, 0x9a, 0xa1, 0x3c, 0xc3, 0x5c, 0xb8, 0x56, 0xe7, 0x84,
	0xf2, 0xec, 0xb5, 0x61, 0x0e, 0x6f, 0x1a, 0xe6, 0xdb, 0xd0, 0x8e, 0x04, 0xcf, 0x9e, 0xa1, 0xc1,
	0xc6, 0xe2, 0x39, 0x40, 0xd8, 0x28, 0xc2, 0x41, 0x6e, 0xd4, 0x66, 0x10, 0xb0, 0x7e, 0x6d, 0xb0,
	0x16, 0x00, 0x41, 0x34, 0xed, 0xd0, 0x5f, 0xbf, 0xc8, 0x79, 0x84, 0xfe, 0x97, 0x2b, 0x4f, 0x12,
	0xc4, 0x46, 0x11, 0xfb, 0x08, 0xba, 0x46, 0x3d, 0x4f, 0xb5, 0x24, 0x7a, 0xb8, 0x62, 0x8d, 0xd6,
	0x48, 0x73, 0x58, 0x28, 0x98, 0xbf, 0x44, 0xb6, 0x9b, 0x8b, 0xfe, 0xae, 0x10, 0xee, 0x27, 0xb0,
	0x11, 0xe6, 0x3a, 0x4b, 0x67, 0xe3, 0x8a, 0xe9, 0x35, 0xea, 0xb4, 0x9e, 0x51, 0x2c, 0x48, 0x16,
	0xd3, 0x4e, 0xec, 0xa7, 0xe9, 0x7d, 0xe1, 0x04, 0x85, 0xc4, 0x3e, 0x86, 0xa6, 0xc6, 0xca, 0xd6,
	0xf4, 0xb2, 0xe8, 0x0c, 0x99, 0xbd, 0x67, 0x5b, 0xf0, 0x41, 0x61, 0xc1, 0x3e, 0x87, 0xce, 0x4c,
	0xea, 0x70, 0x9c, 0x61, 0xbd, 0x6a, 0xcf, 0x23, 0x87, 0x4d, 0xeb, 0xb0, 0x54, 0xce, 0x01, 0xcc,
	0xca, 0xa5, 0x66, 0x9f, 0x82, 0x13, 0x62, 0xa3, 0x7b, 0x3d, 0xaa, 0xa5, 0x65, 0x17, 0x4b, 0x01,
	0x81, 0x31, 0x42, 0xfa, 0x3c, 0xc9, 0x95, 0x4a, 0x5f, 0x6a, 0xef, 0x2a, 0xc5, 0x5a, 0x8a, 0xfe,
	0xef, 0xb5, 0xe2, 0x75, 0x59, 0x16, 0x3f, 0x3d, 0x02, 0xb6, 0xed, 0xd1, 0x6a, 0xd5, 0xd1, 0x5b,
	0x9e, 0x70, 0xdb, 0x9e, 0x70, 0x69, 0x72, 0x97, 0x87, 0xba, 0xb5, 0x94, 0xe9, 0xa5, 0xe1, 0x5d,
	0x4d, 0xf6, 0x87, 0xcb, 0x67, 0x5f, 0x59, 0xb2, 0x5b, 0x1c, 0xd5, 0xff, 0xb5, 0x06, 0x5d, 0x0a,
	0xf1, 0x88, 0x2e, 0x1d, 0x1b, 0xf4, 0x7a, 0xa5, 0x2a, 0x4c, 0x87, 0xda, 0x8a, 0x78, 0xc7, 0x1e,
	0xbb, 0x02, 0x0e, 0x8f, 0x25, 0xd7, 0x05, 0x8f, 0x1a, 0x01, 0xf3, 0x34, 0x13, 0xb3, 0x13, 0xa1,
	0xcc, 0xbb, 0x78, 0x23, 0x28, 0x45, 0xff, 0x09, 0x74, 0xed, 0xcc, 0xa2, 0x47, 0xc7, 0xdb, 0x49,
	0xc2, 0x4e, 0xed, 0x92, 0xbc, 0x68, 0x18, 0x5a, 0xee, 0xc1, 0x9e, 0x6e, 0x17, 0xdc, 0xf3, 0xb0,
	0xfe, 0x6d, 0xe3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xf6, 0x7f, 0x7b, 0x8c, 0x0c, 0x00,
	0x00,
}
