// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CoreProtocol.proto

package dfproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CoreTextFragment_Color int32

const (
	CoreTextFragment_COLOR_BLACK        CoreTextFragment_Color = 0
	CoreTextFragment_COLOR_BLUE         CoreTextFragment_Color = 1
	CoreTextFragment_COLOR_GREEN        CoreTextFragment_Color = 2
	CoreTextFragment_COLOR_CYAN         CoreTextFragment_Color = 3
	CoreTextFragment_COLOR_RED          CoreTextFragment_Color = 4
	CoreTextFragment_COLOR_MAGENTA      CoreTextFragment_Color = 5
	CoreTextFragment_COLOR_BROWN        CoreTextFragment_Color = 6
	CoreTextFragment_COLOR_GREY         CoreTextFragment_Color = 7
	CoreTextFragment_COLOR_DARKGREY     CoreTextFragment_Color = 8
	CoreTextFragment_COLOR_LIGHTBLUE    CoreTextFragment_Color = 9
	CoreTextFragment_COLOR_LIGHTGREEN   CoreTextFragment_Color = 10
	CoreTextFragment_COLOR_LIGHTCYAN    CoreTextFragment_Color = 11
	CoreTextFragment_COLOR_LIGHTRED     CoreTextFragment_Color = 12
	CoreTextFragment_COLOR_LIGHTMAGENTA CoreTextFragment_Color = 13
	CoreTextFragment_COLOR_YELLOW       CoreTextFragment_Color = 14
	CoreTextFragment_COLOR_WHITE        CoreTextFragment_Color = 15
)

var CoreTextFragment_Color_name = map[int32]string{
	0:  "COLOR_BLACK",
	1:  "COLOR_BLUE",
	2:  "COLOR_GREEN",
	3:  "COLOR_CYAN",
	4:  "COLOR_RED",
	5:  "COLOR_MAGENTA",
	6:  "COLOR_BROWN",
	7:  "COLOR_GREY",
	8:  "COLOR_DARKGREY",
	9:  "COLOR_LIGHTBLUE",
	10: "COLOR_LIGHTGREEN",
	11: "COLOR_LIGHTCYAN",
	12: "COLOR_LIGHTRED",
	13: "COLOR_LIGHTMAGENTA",
	14: "COLOR_YELLOW",
	15: "COLOR_WHITE",
}
var CoreTextFragment_Color_value = map[string]int32{
	"COLOR_BLACK":        0,
	"COLOR_BLUE":         1,
	"COLOR_GREEN":        2,
	"COLOR_CYAN":         3,
	"COLOR_RED":          4,
	"COLOR_MAGENTA":      5,
	"COLOR_BROWN":        6,
	"COLOR_GREY":         7,
	"COLOR_DARKGREY":     8,
	"COLOR_LIGHTBLUE":    9,
	"COLOR_LIGHTGREEN":   10,
	"COLOR_LIGHTCYAN":    11,
	"COLOR_LIGHTRED":     12,
	"COLOR_LIGHTMAGENTA": 13,
	"COLOR_YELLOW":       14,
	"COLOR_WHITE":        15,
}

func (x CoreTextFragment_Color) Enum() *CoreTextFragment_Color {
	p := new(CoreTextFragment_Color)
	*p = x
	return p
}
func (x CoreTextFragment_Color) String() string {
	return proto.EnumName(CoreTextFragment_Color_name, int32(x))
}
func (x *CoreTextFragment_Color) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CoreTextFragment_Color_value, data, "CoreTextFragment_Color")
	if err != nil {
		return err
	}
	*x = CoreTextFragment_Color(value)
	return nil
}
func (CoreTextFragment_Color) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_CoreProtocol_56e7f2b36932186d, []int{0, 0}
}

type CoreErrorNotification_ErrorCode int32

const (
	CoreErrorNotification_CR_LINK_FAILURE    CoreErrorNotification_ErrorCode = -3
	CoreErrorNotification_CR_WOULD_BREAK     CoreErrorNotification_ErrorCode = -2
	CoreErrorNotification_CR_NOT_IMPLEMENTED CoreErrorNotification_ErrorCode = -1
	CoreErrorNotification_CR_OK              CoreErrorNotification_ErrorCode = 0
	CoreErrorNotification_CR_FAILURE         CoreErrorNotification_ErrorCode = 1
	CoreErrorNotification_CR_WRONG_USAGE     CoreErrorNotification_ErrorCode = 2
	CoreErrorNotification_CR_NOT_FOUND       CoreErrorNotification_ErrorCode = 3
)

var CoreErrorNotification_ErrorCode_name = map[int32]string{
	-3: "CR_LINK_FAILURE",
	-2: "CR_WOULD_BREAK",
	-1: "CR_NOT_IMPLEMENTED",
	0:  "CR_OK",
	1:  "CR_FAILURE",
	2:  "CR_WRONG_USAGE",
	3:  "CR_NOT_FOUND",
}
var CoreErrorNotification_ErrorCode_value = map[string]int32{
	"CR_LINK_FAILURE":    -3,
	"CR_WOULD_BREAK":     -2,
	"CR_NOT_IMPLEMENTED": -1,
	"CR_OK":              0,
	"CR_FAILURE":         1,
	"CR_WRONG_USAGE":     2,
	"CR_NOT_FOUND":       3,
}

func (x CoreErrorNotification_ErrorCode) Enum() *CoreErrorNotification_ErrorCode {
	p := new(CoreErrorNotification_ErrorCode)
	*p = x
	return p
}
func (x CoreErrorNotification_ErrorCode) String() string {
	return proto.EnumName(CoreErrorNotification_ErrorCode_name, int32(x))
}
func (x *CoreErrorNotification_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CoreErrorNotification_ErrorCode_value, data, "CoreErrorNotification_ErrorCode")
	if err != nil {
		return err
	}
	*x = CoreErrorNotification_ErrorCode(value)
	return nil
}
func (CoreErrorNotification_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_CoreProtocol_56e7f2b36932186d, []int{2, 0}
}

type CoreTextFragment struct {
	Text                 *string                 `protobuf:"bytes,1,req,name=text" json:"text,omitempty"`
	Color                *CoreTextFragment_Color `protobuf:"varint,2,opt,name=color,enum=dfproto.CoreTextFragment_Color" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CoreTextFragment) Reset()         { *m = CoreTextFragment{} }
func (m *CoreTextFragment) String() string { return proto.CompactTextString(m) }
func (*CoreTextFragment) ProtoMessage()    {}
func (*CoreTextFragment) Descriptor() ([]byte, []int) {
	return fileDescriptor_CoreProtocol_56e7f2b36932186d, []int{0}
}
func (m *CoreTextFragment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoreTextFragment.Unmarshal(m, b)
}
func (m *CoreTextFragment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoreTextFragment.Marshal(b, m, deterministic)
}
func (dst *CoreTextFragment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoreTextFragment.Merge(dst, src)
}
func (m *CoreTextFragment) XXX_Size() int {
	return xxx_messageInfo_CoreTextFragment.Size(m)
}
func (m *CoreTextFragment) XXX_DiscardUnknown() {
	xxx_messageInfo_CoreTextFragment.DiscardUnknown(m)
}

var xxx_messageInfo_CoreTextFragment proto.InternalMessageInfo

func (m *CoreTextFragment) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *CoreTextFragment) GetColor() CoreTextFragment_Color {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return CoreTextFragment_COLOR_BLACK
}

type CoreTextNotification struct {
	Fragments            []*CoreTextFragment `protobuf:"bytes,1,rep,name=fragments" json:"fragments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CoreTextNotification) Reset()         { *m = CoreTextNotification{} }
func (m *CoreTextNotification) String() string { return proto.CompactTextString(m) }
func (*CoreTextNotification) ProtoMessage()    {}
func (*CoreTextNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_CoreProtocol_56e7f2b36932186d, []int{1}
}
func (m *CoreTextNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoreTextNotification.Unmarshal(m, b)
}
func (m *CoreTextNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoreTextNotification.Marshal(b, m, deterministic)
}
func (dst *CoreTextNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoreTextNotification.Merge(dst, src)
}
func (m *CoreTextNotification) XXX_Size() int {
	return xxx_messageInfo_CoreTextNotification.Size(m)
}
func (m *CoreTextNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_CoreTextNotification.DiscardUnknown(m)
}

var xxx_messageInfo_CoreTextNotification proto.InternalMessageInfo

func (m *CoreTextNotification) GetFragments() []*CoreTextFragment {
	if m != nil {
		return m.Fragments
	}
	return nil
}

type CoreErrorNotification struct {
	Code                 *CoreErrorNotification_ErrorCode `protobuf:"varint,1,req,name=code,enum=dfproto.CoreErrorNotification_ErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *CoreErrorNotification) Reset()         { *m = CoreErrorNotification{} }
func (m *CoreErrorNotification) String() string { return proto.CompactTextString(m) }
func (*CoreErrorNotification) ProtoMessage()    {}
func (*CoreErrorNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_CoreProtocol_56e7f2b36932186d, []int{2}
}
func (m *CoreErrorNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoreErrorNotification.Unmarshal(m, b)
}
func (m *CoreErrorNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoreErrorNotification.Marshal(b, m, deterministic)
}
func (dst *CoreErrorNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoreErrorNotification.Merge(dst, src)
}
func (m *CoreErrorNotification) XXX_Size() int {
	return xxx_messageInfo_CoreErrorNotification.Size(m)
}
func (m *CoreErrorNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_CoreErrorNotification.DiscardUnknown(m)
}

var xxx_messageInfo_CoreErrorNotification proto.InternalMessageInfo

func (m *CoreErrorNotification) GetCode() CoreErrorNotification_ErrorCode {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return CoreErrorNotification_CR_LINK_FAILURE
}

type EmptyMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyMessage) Reset()         { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()    {}
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_CoreProtocol_56e7f2b36932186d, []int{3}
}
func (m *EmptyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMessage.Unmarshal(m, b)
}
func (m *EmptyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMessage.Marshal(b, m, deterministic)
}
func (dst *EmptyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMessage.Merge(dst, src)
}
func (m *EmptyMessage) XXX_Size() int {
	return xxx_messageInfo_EmptyMessage.Size(m)
}
func (m *EmptyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMessage proto.InternalMessageInfo

type IntMessage struct {
	Value                *int32   `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntMessage) Reset()         { *m = IntMessage{} }
func (m *IntMessage) String() string { return proto.CompactTextString(m) }
func (*IntMessage) ProtoMessage()    {}
func (*IntMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_CoreProtocol_56e7f2b36932186d, []int{4}
}
func (m *IntMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntMessage.Unmarshal(m, b)
}
func (m *IntMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntMessage.Marshal(b, m, deterministic)
}
func (dst *IntMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntMessage.Merge(dst, src)
}
func (m *IntMessage) XXX_Size() int {
	return xxx_messageInfo_IntMessage.Size(m)
}
func (m *IntMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_IntMessage.DiscardUnknown(m)
}

var xxx_messageInfo_IntMessage proto.InternalMessageInfo

func (m *IntMessage) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type IntListMessage struct {
	Value                []int32  `protobuf:"varint,1,rep,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntListMessage) Reset()         { *m = IntListMessage{} }
func (m *IntListMessage) String() string { return proto.CompactTextString(m) }
func (*IntListMessage) ProtoMessage()    {}
func (*IntListMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_CoreProtocol_56e7f2b36932186d, []int{5}
}
func (m *IntListMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntListMessage.Unmarshal(m, b)
}
func (m *IntListMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntListMessage.Marshal(b, m, deterministic)
}
func (dst *IntListMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntListMessage.Merge(dst, src)
}
func (m *IntListMessage) XXX_Size() int {
	return xxx_messageInfo_IntListMessage.Size(m)
}
func (m *IntListMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_IntListMessage.DiscardUnknown(m)
}

var xxx_messageInfo_IntListMessage proto.InternalMessageInfo

func (m *IntListMessage) GetValue() []int32 {
	if m != nil {
		return m.Value
	}
	return nil
}

type StringMessage struct {
	Value                *string  `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMessage) Reset()         { *m = StringMessage{} }
func (m *StringMessage) String() string { return proto.CompactTextString(m) }
func (*StringMessage) ProtoMessage()    {}
func (*StringMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_CoreProtocol_56e7f2b36932186d, []int{6}
}
func (m *StringMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMessage.Unmarshal(m, b)
}
func (m *StringMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMessage.Marshal(b, m, deterministic)
}
func (dst *StringMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMessage.Merge(dst, src)
}
func (m *StringMessage) XXX_Size() int {
	return xxx_messageInfo_StringMessage.Size(m)
}
func (m *StringMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StringMessage proto.InternalMessageInfo

func (m *StringMessage) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type StringListMessage struct {
	Value                []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringListMessage) Reset()         { *m = StringListMessage{} }
func (m *StringListMessage) String() string { return proto.CompactTextString(m) }
func (*StringListMessage) ProtoMessage()    {}
func (*StringListMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_CoreProtocol_56e7f2b36932186d, []int{7}
}
func (m *StringListMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringListMessage.Unmarshal(m, b)
}
func (m *StringListMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringListMessage.Marshal(b, m, deterministic)
}
func (dst *StringListMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringListMessage.Merge(dst, src)
}
func (m *StringListMessage) XXX_Size() int {
	return xxx_messageInfo_StringListMessage.Size(m)
}
func (m *StringListMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StringListMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StringListMessage proto.InternalMessageInfo

func (m *StringListMessage) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

// RPC BindMethod : CoreBindRequest -> CoreBindReply
type CoreBindRequest struct {
	Method               *string  `protobuf:"bytes,1,req,name=method" json:"method,omitempty"`
	InputMsg             *string  `protobuf:"bytes,2,req,name=input_msg,json=inputMsg" json:"input_msg,omitempty"`
	OutputMsg            *string  `protobuf:"bytes,3,req,name=output_msg,json=outputMsg" json:"output_msg,omitempty"`
	Plugin               *string  `protobuf:"bytes,4,opt,name=plugin" json:"plugin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoreBindRequest) Reset()         { *m = CoreBindRequest{} }
func (m *CoreBindRequest) String() string { return proto.CompactTextString(m) }
func (*CoreBindRequest) ProtoMessage()    {}
func (*CoreBindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_CoreProtocol_56e7f2b36932186d, []int{8}
}
func (m *CoreBindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoreBindRequest.Unmarshal(m, b)
}
func (m *CoreBindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoreBindRequest.Marshal(b, m, deterministic)
}
func (dst *CoreBindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoreBindRequest.Merge(dst, src)
}
func (m *CoreBindRequest) XXX_Size() int {
	return xxx_messageInfo_CoreBindRequest.Size(m)
}
func (m *CoreBindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CoreBindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CoreBindRequest proto.InternalMessageInfo

func (m *CoreBindRequest) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *CoreBindRequest) GetInputMsg() string {
	if m != nil && m.InputMsg != nil {
		return *m.InputMsg
	}
	return ""
}

func (m *CoreBindRequest) GetOutputMsg() string {
	if m != nil && m.OutputMsg != nil {
		return *m.OutputMsg
	}
	return ""
}

func (m *CoreBindRequest) GetPlugin() string {
	if m != nil && m.Plugin != nil {
		return *m.Plugin
	}
	return ""
}

type CoreBindReply struct {
	AssignedId           *int32   `protobuf:"varint,1,req,name=assigned_id,json=assignedId" json:"assigned_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoreBindReply) Reset()         { *m = CoreBindReply{} }
func (m *CoreBindReply) String() string { return proto.CompactTextString(m) }
func (*CoreBindReply) ProtoMessage()    {}
func (*CoreBindReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_CoreProtocol_56e7f2b36932186d, []int{9}
}
func (m *CoreBindReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoreBindReply.Unmarshal(m, b)
}
func (m *CoreBindReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoreBindReply.Marshal(b, m, deterministic)
}
func (dst *CoreBindReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoreBindReply.Merge(dst, src)
}
func (m *CoreBindReply) XXX_Size() int {
	return xxx_messageInfo_CoreBindReply.Size(m)
}
func (m *CoreBindReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CoreBindReply.DiscardUnknown(m)
}

var xxx_messageInfo_CoreBindReply proto.InternalMessageInfo

func (m *CoreBindReply) GetAssignedId() int32 {
	if m != nil && m.AssignedId != nil {
		return *m.AssignedId
	}
	return 0
}

// RPC RunCommand : CoreRunCommandRequest -> EmptyMessage
type CoreRunCommandRequest struct {
	Command              *string  `protobuf:"bytes,1,req,name=command" json:"command,omitempty"`
	Arguments            []string `protobuf:"bytes,2,rep,name=arguments" json:"arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoreRunCommandRequest) Reset()         { *m = CoreRunCommandRequest{} }
func (m *CoreRunCommandRequest) String() string { return proto.CompactTextString(m) }
func (*CoreRunCommandRequest) ProtoMessage()    {}
func (*CoreRunCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_CoreProtocol_56e7f2b36932186d, []int{10}
}
func (m *CoreRunCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoreRunCommandRequest.Unmarshal(m, b)
}
func (m *CoreRunCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoreRunCommandRequest.Marshal(b, m, deterministic)
}
func (dst *CoreRunCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoreRunCommandRequest.Merge(dst, src)
}
func (m *CoreRunCommandRequest) XXX_Size() int {
	return xxx_messageInfo_CoreRunCommandRequest.Size(m)
}
func (m *CoreRunCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CoreRunCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CoreRunCommandRequest proto.InternalMessageInfo

func (m *CoreRunCommandRequest) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

func (m *CoreRunCommandRequest) GetArguments() []string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

// RPC RunLua : CoreRunLuaRequest -> StringListMessage
type CoreRunLuaRequest struct {
	Module               *string  `protobuf:"bytes,1,req,name=module" json:"module,omitempty"`
	Function             *string  `protobuf:"bytes,2,req,name=function" json:"function,omitempty"`
	Arguments            []string `protobuf:"bytes,3,rep,name=arguments" json:"arguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoreRunLuaRequest) Reset()         { *m = CoreRunLuaRequest{} }
func (m *CoreRunLuaRequest) String() string { return proto.CompactTextString(m) }
func (*CoreRunLuaRequest) ProtoMessage()    {}
func (*CoreRunLuaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_CoreProtocol_56e7f2b36932186d, []int{11}
}
func (m *CoreRunLuaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoreRunLuaRequest.Unmarshal(m, b)
}
func (m *CoreRunLuaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoreRunLuaRequest.Marshal(b, m, deterministic)
}
func (dst *CoreRunLuaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoreRunLuaRequest.Merge(dst, src)
}
func (m *CoreRunLuaRequest) XXX_Size() int {
	return xxx_messageInfo_CoreRunLuaRequest.Size(m)
}
func (m *CoreRunLuaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CoreRunLuaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CoreRunLuaRequest proto.InternalMessageInfo

func (m *CoreRunLuaRequest) GetModule() string {
	if m != nil && m.Module != nil {
		return *m.Module
	}
	return ""
}

func (m *CoreRunLuaRequest) GetFunction() string {
	if m != nil && m.Function != nil {
		return *m.Function
	}
	return ""
}

func (m *CoreRunLuaRequest) GetArguments() []string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func init() {
	proto.RegisterType((*CoreTextFragment)(nil), "dfproto.CoreTextFragment")
	proto.RegisterType((*CoreTextNotification)(nil), "dfproto.CoreTextNotification")
	proto.RegisterType((*CoreErrorNotification)(nil), "dfproto.CoreErrorNotification")
	proto.RegisterType((*EmptyMessage)(nil), "dfproto.EmptyMessage")
	proto.RegisterType((*IntMessage)(nil), "dfproto.IntMessage")
	proto.RegisterType((*IntListMessage)(nil), "dfproto.IntListMessage")
	proto.RegisterType((*StringMessage)(nil), "dfproto.StringMessage")
	proto.RegisterType((*StringListMessage)(nil), "dfproto.StringListMessage")
	proto.RegisterType((*CoreBindRequest)(nil), "dfproto.CoreBindRequest")
	proto.RegisterType((*CoreBindReply)(nil), "dfproto.CoreBindReply")
	proto.RegisterType((*CoreRunCommandRequest)(nil), "dfproto.CoreRunCommandRequest")
	proto.RegisterType((*CoreRunLuaRequest)(nil), "dfproto.CoreRunLuaRequest")
	proto.RegisterEnum("dfproto.CoreTextFragment_Color", CoreTextFragment_Color_name, CoreTextFragment_Color_value)
	proto.RegisterEnum("dfproto.CoreErrorNotification_ErrorCode", CoreErrorNotification_ErrorCode_name, CoreErrorNotification_ErrorCode_value)
}

func init() { proto.RegisterFile("CoreProtocol.proto", fileDescriptor_CoreProtocol_56e7f2b36932186d) }

var fileDescriptor_CoreProtocol_56e7f2b36932186d = []byte{
	// 690 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x6f, 0x9b, 0x4a,
	0x14, 0x7d, 0x80, 0x9d, 0x84, 0xeb, 0x18, 0x4f, 0xe6, 0xe5, 0x45, 0x7e, 0x2f, 0x79, 0x8a, 0x85,
	0xd4, 0xca, 0xdd, 0x58, 0x55, 0xa4, 0xaa, 0x9b, 0x6e, 0x30, 0x9e, 0x38, 0x96, 0x31, 0x44, 0x13,
	0x5b, 0x56, 0x56, 0x08, 0x19, 0x4c, 0x91, 0x6c, 0x70, 0xf9, 0xa8, 0x92, 0x45, 0xa5, 0xfe, 0x83,
	0xfe, 0x8d, 0xee, 0xfa, 0x0b, 0xdb, 0x54, 0xcc, 0x80, 0x71, 0xd2, 0x84, 0xd5, 0x9c, 0x73, 0x0f,
	0xe7, 0xde, 0x39, 0x73, 0x01, 0xeb, 0x51, 0xec, 0x5d, 0xc7, 0x51, 0x1a, 0x2d, 0xa2, 0x55, 0x6f,
	0x93, 0x1f, 0xf0, 0xbe, 0xbb, 0x64, 0x07, 0xf5, 0x9b, 0x04, 0x28, 0xaf, 0x4f, 0xbd, 0xbb, 0xf4,
	0x32, 0x76, 0xfc, 0xb5, 0x17, 0xa6, 0x18, 0x43, 0x2d, 0xf5, 0xee, 0xd2, 0xb6, 0xd0, 0x11, 0xbb,
	0x32, 0x65, 0x67, 0xfc, 0x0e, 0xea, 0x8b, 0x68, 0x15, 0xc5, 0x6d, 0xb1, 0x23, 0x74, 0x95, 0x8b,
	0xf3, 0x5e, 0xe1, 0xd0, 0x7b, 0xfa, 0x77, 0x4f, 0xcf, 0x65, 0x94, 0xab, 0xd5, 0x1f, 0x22, 0xd4,
	0x19, 0x81, 0x5b, 0xd0, 0xd0, 0x2d, 0xc3, 0xa2, 0x76, 0xdf, 0xd0, 0xf4, 0x31, 0xfa, 0x0b, 0x2b,
	0x00, 0x25, 0x31, 0x23, 0x48, 0xa8, 0x04, 0x43, 0x4a, 0x88, 0x89, 0xc4, 0x4a, 0xa0, 0xdf, 0x6a,
	0x26, 0x92, 0x70, 0x13, 0x64, 0x8e, 0x29, 0x19, 0xa0, 0x1a, 0x3e, 0x82, 0x26, 0x87, 0x13, 0x6d,
	0x48, 0xcc, 0xa9, 0x86, 0xea, 0x3b, 0x3d, 0xa8, 0x35, 0x37, 0xd1, 0x5e, 0x65, 0x31, 0xa4, 0xe4,
	0x16, 0xed, 0x63, 0x0c, 0x0a, 0xc7, 0x03, 0x8d, 0x8e, 0x19, 0x77, 0x80, 0xff, 0x86, 0x16, 0xe7,
	0x8c, 0xd1, 0xf0, 0x6a, 0xca, 0x86, 0x91, 0xf1, 0x31, 0xa0, 0x1d, 0x92, 0x4f, 0x04, 0x4f, 0xa4,
	0x6c, 0xac, 0x46, 0xe5, 0xc9, 0xc8, 0x7c, 0xb6, 0x43, 0x7c, 0x02, 0x78, 0x87, 0x2b, 0x07, 0x6c,
	0x62, 0x04, 0x87, 0x9c, 0xbf, 0x25, 0x86, 0x61, 0xcd, 0x91, 0x52, 0x8d, 0x3c, 0xbf, 0x1a, 0x4d,
	0x09, 0x6a, 0xa9, 0x16, 0x1c, 0x97, 0x91, 0x9a, 0x51, 0x1a, 0x2c, 0x83, 0x85, 0x93, 0x06, 0x51,
	0x88, 0xdf, 0x83, 0xbc, 0x2c, 0x22, 0x4e, 0xda, 0x42, 0x47, 0xea, 0x36, 0x2e, 0xfe, 0x7d, 0xf1,
	0x11, 0x68, 0xa5, 0x55, 0xbf, 0x8a, 0xf0, 0x4f, 0x5e, 0x27, 0x71, 0x1c, 0xc5, 0x8f, 0x2c, 0x3f,
	0x40, 0x6d, 0x11, 0xb9, 0x1e, 0x7b, 0x67, 0xe5, 0xa2, 0xfb, 0xc8, 0xed, 0x0f, 0x75, 0x8f, 0x31,
	0x7a, 0xe4, 0x7a, 0x94, 0xfd, 0xa5, 0x7e, 0x17, 0x40, 0xde, 0x72, 0xf8, 0x0c, 0x5a, 0x7a, 0x7e,
	0x5d, 0x73, 0x6c, 0x5f, 0x6a, 0x23, 0x63, 0x46, 0x09, 0xfa, 0xf9, 0x50, 0x7c, 0x02, 0x3e, 0x05,
	0x45, 0xa7, 0xf6, 0xdc, 0x9a, 0x19, 0x03, 0xbb, 0x4f, 0x89, 0x36, 0x46, 0xbf, 0xaa, 0xe2, 0x39,
	0x60, 0x9d, 0xda, 0xa6, 0x35, 0xb5, 0x47, 0x93, 0x6b, 0x83, 0x4c, 0x88, 0x39, 0x25, 0x03, 0xf4,
	0x50, 0x09, 0x64, 0xa8, 0xeb, 0xd4, 0xb6, 0xca, 0xa5, 0xa1, 0xdb, 0x0e, 0x02, 0x0b, 0x9f, 0xda,
	0x73, 0x6a, 0x99, 0x43, 0x7b, 0x76, 0xa3, 0x0d, 0x09, 0x12, 0x59, 0xc8, 0xdc, 0xef, 0xd2, 0x9a,
	0x99, 0x03, 0x24, 0xa9, 0x0a, 0x1c, 0x92, 0xf5, 0x26, 0xbd, 0x9f, 0x78, 0x49, 0xe2, 0xf8, 0x9e,
	0xaa, 0x02, 0x8c, 0xc2, 0xb4, 0x40, 0xf8, 0x18, 0xea, 0x9f, 0x9d, 0x55, 0xc6, 0x73, 0xa8, 0x53,
	0x0e, 0xd4, 0xd7, 0xa0, 0x8c, 0xc2, 0xd4, 0x08, 0x92, 0xe7, 0x74, 0x52, 0xa5, 0x7b, 0x05, 0xcd,
	0x9b, 0x34, 0x0e, 0x42, 0xff, 0x59, 0x3b, 0xb9, 0x94, 0xbd, 0x81, 0x23, 0x2e, 0x7b, 0xd1, 0x71,
	0x2b, 0xfd, 0x02, 0xad, 0xfc, 0x05, 0xfa, 0x41, 0xe8, 0x52, 0xef, 0x53, 0xe6, 0x25, 0x29, 0x3e,
	0x81, 0xbd, 0xb5, 0x97, 0x7e, 0x8c, 0xdc, 0xc2, 0xb4, 0x40, 0xf8, 0x14, 0xe4, 0x20, 0xdc, 0x64,
	0xa9, 0xbd, 0x4e, 0xfc, 0xb6, 0xc8, 0x4a, 0x07, 0x8c, 0x98, 0x24, 0x3e, 0xfe, 0x1f, 0x20, 0xca,
	0xd2, 0xb2, 0x2a, 0xb1, 0xaa, 0xcc, 0x99, 0xbc, 0x7c, 0x02, 0x7b, 0x9b, 0x55, 0xe6, 0x07, 0x61,
	0xbb, 0xd6, 0x11, 0x72, 0x4f, 0x8e, 0xd4, 0xb7, 0xd0, 0xac, 0xda, 0x6f, 0x56, 0xf7, 0xf8, 0x1c,
	0x1a, 0x4e, 0x92, 0x04, 0x7e, 0xe8, 0xb9, 0x76, 0xe0, 0x16, 0x29, 0x41, 0x49, 0x8d, 0x5c, 0xd5,
	0xe2, 0x0b, 0x46, 0xb3, 0x50, 0x8f, 0xd6, 0x6b, 0xa7, 0x1a, 0xbb, 0x0d, 0xfb, 0x0b, 0xce, 0x14,
	0x73, 0x97, 0x10, 0x9f, 0x81, 0xec, 0xc4, 0x7e, 0xc6, 0xb7, 0x59, 0x64, 0xb7, 0xaf, 0x08, 0xd5,
	0x83, 0xa3, 0xc2, 0xd0, 0xc8, 0x9c, 0xdd, 0x0c, 0x22, 0x37, 0x5b, 0x79, 0xdb, 0x0c, 0x18, 0xc2,
	0xff, 0xc1, 0xc1, 0x32, 0x0b, 0x17, 0xf9, 0x8e, 0x96, 0x11, 0x94, 0xf8, 0x71, 0x1b, 0xe9, 0x49,
	0x9b, 0xbe, 0x78, 0x25, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x68, 0x04, 0x07, 0x0a, 0x1e, 0x05,
	0x00, 0x00,
}
