// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stockpiles.proto

package dfproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StockpileSettings struct {
	Animals        *StockpileSettings_AnimalsSet       `protobuf:"bytes,1,opt,name=animals" json:"animals,omitempty"`
	Food           *StockpileSettings_FoodSet          `protobuf:"bytes,2,opt,name=food" json:"food,omitempty"`
	Furniture      *StockpileSettings_FurnitureSet     `protobuf:"bytes,3,opt,name=furniture" json:"furniture,omitempty"`
	Unknown1       *int32                              `protobuf:"varint,4,opt,name=unknown1" json:"unknown1,omitempty"`
	Refuse         *StockpileSettings_RefuseSet        `protobuf:"bytes,5,opt,name=refuse" json:"refuse,omitempty"`
	Stone          *StockpileSettings_StoneSet         `protobuf:"bytes,6,opt,name=stone" json:"stone,omitempty"`
	Ore            *StockpileSettings_OreSet           `protobuf:"bytes,7,opt,name=ore" json:"ore,omitempty"`
	Ammo           *StockpileSettings_AmmoSet          `protobuf:"bytes,8,opt,name=ammo" json:"ammo,omitempty"`
	Coin           *StockpileSettings_CoinSet          `protobuf:"bytes,9,opt,name=coin" json:"coin,omitempty"`
	Barsblocks     *StockpileSettings_BarsBlocksSet    `protobuf:"bytes,10,opt,name=barsblocks" json:"barsblocks,omitempty"`
	Gems           *StockpileSettings_GemsSet          `protobuf:"bytes,11,opt,name=gems" json:"gems,omitempty"`
	FinishedGoods  *StockpileSettings_FinishedGoodsSet `protobuf:"bytes,12,opt,name=finished_goods,json=finishedGoods" json:"finished_goods,omitempty"`
	Leather        *StockpileSettings_LeatherSet       `protobuf:"bytes,13,opt,name=leather" json:"leather,omitempty"`
	Cloth          *StockpileSettings_ClothSet         `protobuf:"bytes,14,opt,name=cloth" json:"cloth,omitempty"`
	Wood           *StockpileSettings_WoodSet          `protobuf:"bytes,15,opt,name=wood" json:"wood,omitempty"`
	Weapons        *StockpileSettings_WeaponsSet       `protobuf:"bytes,16,opt,name=weapons" json:"weapons,omitempty"`
	Armor          *StockpileSettings_ArmorSet         `protobuf:"bytes,17,opt,name=armor" json:"armor,omitempty"`
	AllowOrganic   *bool                               `protobuf:"varint,18,opt,name=allow_organic,json=allowOrganic" json:"allow_organic,omitempty"`
	AllowInorganic *bool                               `protobuf:"varint,19,opt,name=allow_inorganic,json=allowInorganic" json:"allow_inorganic,omitempty"`
	Corpses        *bool                               `protobuf:"varint,24,opt,name=corpses" json:"corpses,omitempty"`
	// extras
	MaxBarrels           *int32   `protobuf:"varint,20,opt,name=max_barrels,json=maxBarrels" json:"max_barrels,omitempty"`
	MaxBins              *int32   `protobuf:"varint,21,opt,name=max_bins,json=maxBins" json:"max_bins,omitempty"`
	MaxWheelbarrows      *int32   `protobuf:"varint,22,opt,name=max_wheelbarrows,json=maxWheelbarrows" json:"max_wheelbarrows,omitempty"`
	UseLinksOnly         *bool    `protobuf:"varint,23,opt,name=use_links_only,json=useLinksOnly" json:"use_links_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings) Reset()         { *m = StockpileSettings{} }
func (m *StockpileSettings) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings) ProtoMessage()    {}
func (*StockpileSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0}
}
func (m *StockpileSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings.Unmarshal(m, b)
}
func (m *StockpileSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings.Merge(dst, src)
}
func (m *StockpileSettings) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings.Size(m)
}
func (m *StockpileSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings proto.InternalMessageInfo

func (m *StockpileSettings) GetAnimals() *StockpileSettings_AnimalsSet {
	if m != nil {
		return m.Animals
	}
	return nil
}

func (m *StockpileSettings) GetFood() *StockpileSettings_FoodSet {
	if m != nil {
		return m.Food
	}
	return nil
}

func (m *StockpileSettings) GetFurniture() *StockpileSettings_FurnitureSet {
	if m != nil {
		return m.Furniture
	}
	return nil
}

func (m *StockpileSettings) GetUnknown1() int32 {
	if m != nil && m.Unknown1 != nil {
		return *m.Unknown1
	}
	return 0
}

func (m *StockpileSettings) GetRefuse() *StockpileSettings_RefuseSet {
	if m != nil {
		return m.Refuse
	}
	return nil
}

func (m *StockpileSettings) GetStone() *StockpileSettings_StoneSet {
	if m != nil {
		return m.Stone
	}
	return nil
}

func (m *StockpileSettings) GetOre() *StockpileSettings_OreSet {
	if m != nil {
		return m.Ore
	}
	return nil
}

func (m *StockpileSettings) GetAmmo() *StockpileSettings_AmmoSet {
	if m != nil {
		return m.Ammo
	}
	return nil
}

func (m *StockpileSettings) GetCoin() *StockpileSettings_CoinSet {
	if m != nil {
		return m.Coin
	}
	return nil
}

func (m *StockpileSettings) GetBarsblocks() *StockpileSettings_BarsBlocksSet {
	if m != nil {
		return m.Barsblocks
	}
	return nil
}

func (m *StockpileSettings) GetGems() *StockpileSettings_GemsSet {
	if m != nil {
		return m.Gems
	}
	return nil
}

func (m *StockpileSettings) GetFinishedGoods() *StockpileSettings_FinishedGoodsSet {
	if m != nil {
		return m.FinishedGoods
	}
	return nil
}

func (m *StockpileSettings) GetLeather() *StockpileSettings_LeatherSet {
	if m != nil {
		return m.Leather
	}
	return nil
}

func (m *StockpileSettings) GetCloth() *StockpileSettings_ClothSet {
	if m != nil {
		return m.Cloth
	}
	return nil
}

func (m *StockpileSettings) GetWood() *StockpileSettings_WoodSet {
	if m != nil {
		return m.Wood
	}
	return nil
}

func (m *StockpileSettings) GetWeapons() *StockpileSettings_WeaponsSet {
	if m != nil {
		return m.Weapons
	}
	return nil
}

func (m *StockpileSettings) GetArmor() *StockpileSettings_ArmorSet {
	if m != nil {
		return m.Armor
	}
	return nil
}

func (m *StockpileSettings) GetAllowOrganic() bool {
	if m != nil && m.AllowOrganic != nil {
		return *m.AllowOrganic
	}
	return false
}

func (m *StockpileSettings) GetAllowInorganic() bool {
	if m != nil && m.AllowInorganic != nil {
		return *m.AllowInorganic
	}
	return false
}

func (m *StockpileSettings) GetCorpses() bool {
	if m != nil && m.Corpses != nil {
		return *m.Corpses
	}
	return false
}

func (m *StockpileSettings) GetMaxBarrels() int32 {
	if m != nil && m.MaxBarrels != nil {
		return *m.MaxBarrels
	}
	return 0
}

func (m *StockpileSettings) GetMaxBins() int32 {
	if m != nil && m.MaxBins != nil {
		return *m.MaxBins
	}
	return 0
}

func (m *StockpileSettings) GetMaxWheelbarrows() int32 {
	if m != nil && m.MaxWheelbarrows != nil {
		return *m.MaxWheelbarrows
	}
	return 0
}

func (m *StockpileSettings) GetUseLinksOnly() bool {
	if m != nil && m.UseLinksOnly != nil {
		return *m.UseLinksOnly
	}
	return false
}

type StockpileSettings_AnimalsSet struct {
	EmptyCages           *bool    `protobuf:"varint,1,opt,name=empty_cages,json=emptyCages" json:"empty_cages,omitempty"`
	EmptyTraps           *bool    `protobuf:"varint,2,opt,name=empty_traps,json=emptyTraps" json:"empty_traps,omitempty"`
	Enabled              []string `protobuf:"bytes,3,rep,name=enabled" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_AnimalsSet) Reset()         { *m = StockpileSettings_AnimalsSet{} }
func (m *StockpileSettings_AnimalsSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_AnimalsSet) ProtoMessage()    {}
func (*StockpileSettings_AnimalsSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 0}
}
func (m *StockpileSettings_AnimalsSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_AnimalsSet.Unmarshal(m, b)
}
func (m *StockpileSettings_AnimalsSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_AnimalsSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_AnimalsSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_AnimalsSet.Merge(dst, src)
}
func (m *StockpileSettings_AnimalsSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_AnimalsSet.Size(m)
}
func (m *StockpileSettings_AnimalsSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_AnimalsSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_AnimalsSet proto.InternalMessageInfo

func (m *StockpileSettings_AnimalsSet) GetEmptyCages() bool {
	if m != nil && m.EmptyCages != nil {
		return *m.EmptyCages
	}
	return false
}

func (m *StockpileSettings_AnimalsSet) GetEmptyTraps() bool {
	if m != nil && m.EmptyTraps != nil {
		return *m.EmptyTraps
	}
	return false
}

func (m *StockpileSettings_AnimalsSet) GetEnabled() []string {
	if m != nil {
		return m.Enabled
	}
	return nil
}

type StockpileSettings_FoodSet struct {
	Meat                 []string `protobuf:"bytes,1,rep,name=meat" json:"meat,omitempty"`
	Fish                 []string `protobuf:"bytes,2,rep,name=fish" json:"fish,omitempty"`
	UnpreparedFish       []string `protobuf:"bytes,20,rep,name=unprepared_fish,json=unpreparedFish" json:"unprepared_fish,omitempty"`
	Egg                  []string `protobuf:"bytes,3,rep,name=egg" json:"egg,omitempty"`
	Plants               []string `protobuf:"bytes,4,rep,name=plants" json:"plants,omitempty"`
	DrinkPlant           []string `protobuf:"bytes,5,rep,name=drink_plant,json=drinkPlant" json:"drink_plant,omitempty"`
	DrinkAnimal          []string `protobuf:"bytes,6,rep,name=drink_animal,json=drinkAnimal" json:"drink_animal,omitempty"`
	CheesePlant          []string `protobuf:"bytes,7,rep,name=cheese_plant,json=cheesePlant" json:"cheese_plant,omitempty"`
	CheeseAnimal         []string `protobuf:"bytes,8,rep,name=cheese_animal,json=cheeseAnimal" json:"cheese_animal,omitempty"`
	Seeds                []string `protobuf:"bytes,9,rep,name=seeds" json:"seeds,omitempty"`
	Leaves               []string `protobuf:"bytes,10,rep,name=leaves" json:"leaves,omitempty"`
	PowderPlant          []string `protobuf:"bytes,11,rep,name=powder_plant,json=powderPlant" json:"powder_plant,omitempty"`
	PowderCreature       []string `protobuf:"bytes,12,rep,name=powder_creature,json=powderCreature" json:"powder_creature,omitempty"`
	Glob                 []string `protobuf:"bytes,13,rep,name=glob" json:"glob,omitempty"`
	GlobPaste            []string `protobuf:"bytes,14,rep,name=glob_paste,json=globPaste" json:"glob_paste,omitempty"`
	GlobPressed          []string `protobuf:"bytes,15,rep,name=glob_pressed,json=globPressed" json:"glob_pressed,omitempty"`
	LiquidPlant          []string `protobuf:"bytes,16,rep,name=liquid_plant,json=liquidPlant" json:"liquid_plant,omitempty"`
	LiquidAnimal         []string `protobuf:"bytes,17,rep,name=liquid_animal,json=liquidAnimal" json:"liquid_animal,omitempty"`
	LiquidMisc           []string `protobuf:"bytes,18,rep,name=liquid_misc,json=liquidMisc" json:"liquid_misc,omitempty"`
	PreparedMeals        *bool    `protobuf:"varint,19,opt,name=prepared_meals,json=preparedMeals" json:"prepared_meals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_FoodSet) Reset()         { *m = StockpileSettings_FoodSet{} }
func (m *StockpileSettings_FoodSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_FoodSet) ProtoMessage()    {}
func (*StockpileSettings_FoodSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 1}
}
func (m *StockpileSettings_FoodSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_FoodSet.Unmarshal(m, b)
}
func (m *StockpileSettings_FoodSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_FoodSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_FoodSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_FoodSet.Merge(dst, src)
}
func (m *StockpileSettings_FoodSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_FoodSet.Size(m)
}
func (m *StockpileSettings_FoodSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_FoodSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_FoodSet proto.InternalMessageInfo

func (m *StockpileSettings_FoodSet) GetMeat() []string {
	if m != nil {
		return m.Meat
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetFish() []string {
	if m != nil {
		return m.Fish
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetUnpreparedFish() []string {
	if m != nil {
		return m.UnpreparedFish
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetEgg() []string {
	if m != nil {
		return m.Egg
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetPlants() []string {
	if m != nil {
		return m.Plants
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetDrinkPlant() []string {
	if m != nil {
		return m.DrinkPlant
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetDrinkAnimal() []string {
	if m != nil {
		return m.DrinkAnimal
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetCheesePlant() []string {
	if m != nil {
		return m.CheesePlant
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetCheeseAnimal() []string {
	if m != nil {
		return m.CheeseAnimal
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetSeeds() []string {
	if m != nil {
		return m.Seeds
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetLeaves() []string {
	if m != nil {
		return m.Leaves
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetPowderPlant() []string {
	if m != nil {
		return m.PowderPlant
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetPowderCreature() []string {
	if m != nil {
		return m.PowderCreature
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetGlob() []string {
	if m != nil {
		return m.Glob
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetGlobPaste() []string {
	if m != nil {
		return m.GlobPaste
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetGlobPressed() []string {
	if m != nil {
		return m.GlobPressed
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetLiquidPlant() []string {
	if m != nil {
		return m.LiquidPlant
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetLiquidAnimal() []string {
	if m != nil {
		return m.LiquidAnimal
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetLiquidMisc() []string {
	if m != nil {
		return m.LiquidMisc
	}
	return nil
}

func (m *StockpileSettings_FoodSet) GetPreparedMeals() bool {
	if m != nil && m.PreparedMeals != nil {
		return *m.PreparedMeals
	}
	return false
}

type StockpileSettings_FurnitureSet struct {
	Type                 []string `protobuf:"bytes,1,rep,name=type" json:"type,omitempty"`
	OtherMats            []string `protobuf:"bytes,2,rep,name=other_mats,json=otherMats" json:"other_mats,omitempty"`
	Mats                 []string `protobuf:"bytes,3,rep,name=mats" json:"mats,omitempty"`
	QualityCore          []string `protobuf:"bytes,4,rep,name=quality_core,json=qualityCore" json:"quality_core,omitempty"`
	QualityTotal         []string `protobuf:"bytes,5,rep,name=quality_total,json=qualityTotal" json:"quality_total,omitempty"`
	SandBags             *bool    `protobuf:"varint,6,opt,name=sand_bags,json=sandBags" json:"sand_bags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_FurnitureSet) Reset()         { *m = StockpileSettings_FurnitureSet{} }
func (m *StockpileSettings_FurnitureSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_FurnitureSet) ProtoMessage()    {}
func (*StockpileSettings_FurnitureSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 2}
}
func (m *StockpileSettings_FurnitureSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_FurnitureSet.Unmarshal(m, b)
}
func (m *StockpileSettings_FurnitureSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_FurnitureSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_FurnitureSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_FurnitureSet.Merge(dst, src)
}
func (m *StockpileSettings_FurnitureSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_FurnitureSet.Size(m)
}
func (m *StockpileSettings_FurnitureSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_FurnitureSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_FurnitureSet proto.InternalMessageInfo

func (m *StockpileSettings_FurnitureSet) GetType() []string {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *StockpileSettings_FurnitureSet) GetOtherMats() []string {
	if m != nil {
		return m.OtherMats
	}
	return nil
}

func (m *StockpileSettings_FurnitureSet) GetMats() []string {
	if m != nil {
		return m.Mats
	}
	return nil
}

func (m *StockpileSettings_FurnitureSet) GetQualityCore() []string {
	if m != nil {
		return m.QualityCore
	}
	return nil
}

func (m *StockpileSettings_FurnitureSet) GetQualityTotal() []string {
	if m != nil {
		return m.QualityTotal
	}
	return nil
}

func (m *StockpileSettings_FurnitureSet) GetSandBags() bool {
	if m != nil && m.SandBags != nil {
		return *m.SandBags
	}
	return false
}

type StockpileSettings_RefuseSet struct {
	Type                 []string `protobuf:"bytes,1,rep,name=type" json:"type,omitempty"`
	Corpses              []string `protobuf:"bytes,2,rep,name=corpses" json:"corpses,omitempty"`
	BodyParts            []string `protobuf:"bytes,3,rep,name=body_parts,json=bodyParts" json:"body_parts,omitempty"`
	Skulls               []string `protobuf:"bytes,4,rep,name=skulls" json:"skulls,omitempty"`
	Bones                []string `protobuf:"bytes,5,rep,name=bones" json:"bones,omitempty"`
	Hair                 []string `protobuf:"bytes,6,rep,name=hair" json:"hair,omitempty"`
	Shells               []string `protobuf:"bytes,7,rep,name=shells" json:"shells,omitempty"`
	Teeth                []string `protobuf:"bytes,8,rep,name=teeth" json:"teeth,omitempty"`
	Horns                []string `protobuf:"bytes,9,rep,name=horns" json:"horns,omitempty"`
	FreshRawHide         *bool    `protobuf:"varint,10,opt,name=fresh_raw_hide,json=freshRawHide" json:"fresh_raw_hide,omitempty"`
	RottenRawHide        *bool    `protobuf:"varint,11,opt,name=rotten_raw_hide,json=rottenRawHide" json:"rotten_raw_hide,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_RefuseSet) Reset()         { *m = StockpileSettings_RefuseSet{} }
func (m *StockpileSettings_RefuseSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_RefuseSet) ProtoMessage()    {}
func (*StockpileSettings_RefuseSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 3}
}
func (m *StockpileSettings_RefuseSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_RefuseSet.Unmarshal(m, b)
}
func (m *StockpileSettings_RefuseSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_RefuseSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_RefuseSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_RefuseSet.Merge(dst, src)
}
func (m *StockpileSettings_RefuseSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_RefuseSet.Size(m)
}
func (m *StockpileSettings_RefuseSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_RefuseSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_RefuseSet proto.InternalMessageInfo

func (m *StockpileSettings_RefuseSet) GetType() []string {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *StockpileSettings_RefuseSet) GetCorpses() []string {
	if m != nil {
		return m.Corpses
	}
	return nil
}

func (m *StockpileSettings_RefuseSet) GetBodyParts() []string {
	if m != nil {
		return m.BodyParts
	}
	return nil
}

func (m *StockpileSettings_RefuseSet) GetSkulls() []string {
	if m != nil {
		return m.Skulls
	}
	return nil
}

func (m *StockpileSettings_RefuseSet) GetBones() []string {
	if m != nil {
		return m.Bones
	}
	return nil
}

func (m *StockpileSettings_RefuseSet) GetHair() []string {
	if m != nil {
		return m.Hair
	}
	return nil
}

func (m *StockpileSettings_RefuseSet) GetShells() []string {
	if m != nil {
		return m.Shells
	}
	return nil
}

func (m *StockpileSettings_RefuseSet) GetTeeth() []string {
	if m != nil {
		return m.Teeth
	}
	return nil
}

func (m *StockpileSettings_RefuseSet) GetHorns() []string {
	if m != nil {
		return m.Horns
	}
	return nil
}

func (m *StockpileSettings_RefuseSet) GetFreshRawHide() bool {
	if m != nil && m.FreshRawHide != nil {
		return *m.FreshRawHide
	}
	return false
}

func (m *StockpileSettings_RefuseSet) GetRottenRawHide() bool {
	if m != nil && m.RottenRawHide != nil {
		return *m.RottenRawHide
	}
	return false
}

type StockpileSettings_StoneSet struct {
	Mats                 []string `protobuf:"bytes,1,rep,name=mats" json:"mats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_StoneSet) Reset()         { *m = StockpileSettings_StoneSet{} }
func (m *StockpileSettings_StoneSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_StoneSet) ProtoMessage()    {}
func (*StockpileSettings_StoneSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 4}
}
func (m *StockpileSettings_StoneSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_StoneSet.Unmarshal(m, b)
}
func (m *StockpileSettings_StoneSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_StoneSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_StoneSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_StoneSet.Merge(dst, src)
}
func (m *StockpileSettings_StoneSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_StoneSet.Size(m)
}
func (m *StockpileSettings_StoneSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_StoneSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_StoneSet proto.InternalMessageInfo

func (m *StockpileSettings_StoneSet) GetMats() []string {
	if m != nil {
		return m.Mats
	}
	return nil
}

type StockpileSettings_OreSet struct {
	Mats                 []string `protobuf:"bytes,1,rep,name=mats" json:"mats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_OreSet) Reset()         { *m = StockpileSettings_OreSet{} }
func (m *StockpileSettings_OreSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_OreSet) ProtoMessage()    {}
func (*StockpileSettings_OreSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 5}
}
func (m *StockpileSettings_OreSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_OreSet.Unmarshal(m, b)
}
func (m *StockpileSettings_OreSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_OreSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_OreSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_OreSet.Merge(dst, src)
}
func (m *StockpileSettings_OreSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_OreSet.Size(m)
}
func (m *StockpileSettings_OreSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_OreSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_OreSet proto.InternalMessageInfo

func (m *StockpileSettings_OreSet) GetMats() []string {
	if m != nil {
		return m.Mats
	}
	return nil
}

type StockpileSettings_AmmoSet struct {
	Type                 []string `protobuf:"bytes,1,rep,name=type" json:"type,omitempty"`
	OtherMats            []string `protobuf:"bytes,2,rep,name=other_mats,json=otherMats" json:"other_mats,omitempty"`
	Mats                 []string `protobuf:"bytes,3,rep,name=mats" json:"mats,omitempty"`
	QualityCore          []string `protobuf:"bytes,4,rep,name=quality_core,json=qualityCore" json:"quality_core,omitempty"`
	QualityTotal         []string `protobuf:"bytes,5,rep,name=quality_total,json=qualityTotal" json:"quality_total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_AmmoSet) Reset()         { *m = StockpileSettings_AmmoSet{} }
func (m *StockpileSettings_AmmoSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_AmmoSet) ProtoMessage()    {}
func (*StockpileSettings_AmmoSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 6}
}
func (m *StockpileSettings_AmmoSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_AmmoSet.Unmarshal(m, b)
}
func (m *StockpileSettings_AmmoSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_AmmoSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_AmmoSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_AmmoSet.Merge(dst, src)
}
func (m *StockpileSettings_AmmoSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_AmmoSet.Size(m)
}
func (m *StockpileSettings_AmmoSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_AmmoSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_AmmoSet proto.InternalMessageInfo

func (m *StockpileSettings_AmmoSet) GetType() []string {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *StockpileSettings_AmmoSet) GetOtherMats() []string {
	if m != nil {
		return m.OtherMats
	}
	return nil
}

func (m *StockpileSettings_AmmoSet) GetMats() []string {
	if m != nil {
		return m.Mats
	}
	return nil
}

func (m *StockpileSettings_AmmoSet) GetQualityCore() []string {
	if m != nil {
		return m.QualityCore
	}
	return nil
}

func (m *StockpileSettings_AmmoSet) GetQualityTotal() []string {
	if m != nil {
		return m.QualityTotal
	}
	return nil
}

type StockpileSettings_CoinSet struct {
	Mats                 []string `protobuf:"bytes,1,rep,name=mats" json:"mats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_CoinSet) Reset()         { *m = StockpileSettings_CoinSet{} }
func (m *StockpileSettings_CoinSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_CoinSet) ProtoMessage()    {}
func (*StockpileSettings_CoinSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 7}
}
func (m *StockpileSettings_CoinSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_CoinSet.Unmarshal(m, b)
}
func (m *StockpileSettings_CoinSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_CoinSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_CoinSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_CoinSet.Merge(dst, src)
}
func (m *StockpileSettings_CoinSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_CoinSet.Size(m)
}
func (m *StockpileSettings_CoinSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_CoinSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_CoinSet proto.InternalMessageInfo

func (m *StockpileSettings_CoinSet) GetMats() []string {
	if m != nil {
		return m.Mats
	}
	return nil
}

type StockpileSettings_BarsBlocksSet struct {
	BarsOtherMats        []string `protobuf:"bytes,1,rep,name=bars_other_mats,json=barsOtherMats" json:"bars_other_mats,omitempty"`
	BlocksOtherMats      []string `protobuf:"bytes,2,rep,name=blocks_other_mats,json=blocksOtherMats" json:"blocks_other_mats,omitempty"`
	BarsMats             []string `protobuf:"bytes,3,rep,name=bars_mats,json=barsMats" json:"bars_mats,omitempty"`
	BlocksMats           []string `protobuf:"bytes,4,rep,name=blocks_mats,json=blocksMats" json:"blocks_mats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_BarsBlocksSet) Reset()         { *m = StockpileSettings_BarsBlocksSet{} }
func (m *StockpileSettings_BarsBlocksSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_BarsBlocksSet) ProtoMessage()    {}
func (*StockpileSettings_BarsBlocksSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 8}
}
func (m *StockpileSettings_BarsBlocksSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_BarsBlocksSet.Unmarshal(m, b)
}
func (m *StockpileSettings_BarsBlocksSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_BarsBlocksSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_BarsBlocksSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_BarsBlocksSet.Merge(dst, src)
}
func (m *StockpileSettings_BarsBlocksSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_BarsBlocksSet.Size(m)
}
func (m *StockpileSettings_BarsBlocksSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_BarsBlocksSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_BarsBlocksSet proto.InternalMessageInfo

func (m *StockpileSettings_BarsBlocksSet) GetBarsOtherMats() []string {
	if m != nil {
		return m.BarsOtherMats
	}
	return nil
}

func (m *StockpileSettings_BarsBlocksSet) GetBlocksOtherMats() []string {
	if m != nil {
		return m.BlocksOtherMats
	}
	return nil
}

func (m *StockpileSettings_BarsBlocksSet) GetBarsMats() []string {
	if m != nil {
		return m.BarsMats
	}
	return nil
}

func (m *StockpileSettings_BarsBlocksSet) GetBlocksMats() []string {
	if m != nil {
		return m.BlocksMats
	}
	return nil
}

type StockpileSettings_GemsSet struct {
	RoughOtherMats       []string `protobuf:"bytes,1,rep,name=rough_other_mats,json=roughOtherMats" json:"rough_other_mats,omitempty"`
	CutOtherMats         []string `protobuf:"bytes,2,rep,name=cut_other_mats,json=cutOtherMats" json:"cut_other_mats,omitempty"`
	RoughMats            []string `protobuf:"bytes,3,rep,name=rough_mats,json=roughMats" json:"rough_mats,omitempty"`
	CutMats              []string `protobuf:"bytes,4,rep,name=cut_mats,json=cutMats" json:"cut_mats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_GemsSet) Reset()         { *m = StockpileSettings_GemsSet{} }
func (m *StockpileSettings_GemsSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_GemsSet) ProtoMessage()    {}
func (*StockpileSettings_GemsSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 9}
}
func (m *StockpileSettings_GemsSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_GemsSet.Unmarshal(m, b)
}
func (m *StockpileSettings_GemsSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_GemsSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_GemsSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_GemsSet.Merge(dst, src)
}
func (m *StockpileSettings_GemsSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_GemsSet.Size(m)
}
func (m *StockpileSettings_GemsSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_GemsSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_GemsSet proto.InternalMessageInfo

func (m *StockpileSettings_GemsSet) GetRoughOtherMats() []string {
	if m != nil {
		return m.RoughOtherMats
	}
	return nil
}

func (m *StockpileSettings_GemsSet) GetCutOtherMats() []string {
	if m != nil {
		return m.CutOtherMats
	}
	return nil
}

func (m *StockpileSettings_GemsSet) GetRoughMats() []string {
	if m != nil {
		return m.RoughMats
	}
	return nil
}

func (m *StockpileSettings_GemsSet) GetCutMats() []string {
	if m != nil {
		return m.CutMats
	}
	return nil
}

type StockpileSettings_FinishedGoodsSet struct {
	Type                 []string `protobuf:"bytes,1,rep,name=type" json:"type,omitempty"`
	OtherMats            []string `protobuf:"bytes,2,rep,name=other_mats,json=otherMats" json:"other_mats,omitempty"`
	Mats                 []string `protobuf:"bytes,3,rep,name=mats" json:"mats,omitempty"`
	QualityCore          []string `protobuf:"bytes,4,rep,name=quality_core,json=qualityCore" json:"quality_core,omitempty"`
	QualityTotal         []string `protobuf:"bytes,5,rep,name=quality_total,json=qualityTotal" json:"quality_total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_FinishedGoodsSet) Reset()         { *m = StockpileSettings_FinishedGoodsSet{} }
func (m *StockpileSettings_FinishedGoodsSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_FinishedGoodsSet) ProtoMessage()    {}
func (*StockpileSettings_FinishedGoodsSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 10}
}
func (m *StockpileSettings_FinishedGoodsSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_FinishedGoodsSet.Unmarshal(m, b)
}
func (m *StockpileSettings_FinishedGoodsSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_FinishedGoodsSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_FinishedGoodsSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_FinishedGoodsSet.Merge(dst, src)
}
func (m *StockpileSettings_FinishedGoodsSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_FinishedGoodsSet.Size(m)
}
func (m *StockpileSettings_FinishedGoodsSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_FinishedGoodsSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_FinishedGoodsSet proto.InternalMessageInfo

func (m *StockpileSettings_FinishedGoodsSet) GetType() []string {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *StockpileSettings_FinishedGoodsSet) GetOtherMats() []string {
	if m != nil {
		return m.OtherMats
	}
	return nil
}

func (m *StockpileSettings_FinishedGoodsSet) GetMats() []string {
	if m != nil {
		return m.Mats
	}
	return nil
}

func (m *StockpileSettings_FinishedGoodsSet) GetQualityCore() []string {
	if m != nil {
		return m.QualityCore
	}
	return nil
}

func (m *StockpileSettings_FinishedGoodsSet) GetQualityTotal() []string {
	if m != nil {
		return m.QualityTotal
	}
	return nil
}

type StockpileSettings_LeatherSet struct {
	Mats                 []string `protobuf:"bytes,1,rep,name=mats" json:"mats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_LeatherSet) Reset()         { *m = StockpileSettings_LeatherSet{} }
func (m *StockpileSettings_LeatherSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_LeatherSet) ProtoMessage()    {}
func (*StockpileSettings_LeatherSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 11}
}
func (m *StockpileSettings_LeatherSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_LeatherSet.Unmarshal(m, b)
}
func (m *StockpileSettings_LeatherSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_LeatherSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_LeatherSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_LeatherSet.Merge(dst, src)
}
func (m *StockpileSettings_LeatherSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_LeatherSet.Size(m)
}
func (m *StockpileSettings_LeatherSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_LeatherSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_LeatherSet proto.InternalMessageInfo

func (m *StockpileSettings_LeatherSet) GetMats() []string {
	if m != nil {
		return m.Mats
	}
	return nil
}

type StockpileSettings_ClothSet struct {
	ThreadSilk           []string `protobuf:"bytes,1,rep,name=thread_silk,json=threadSilk" json:"thread_silk,omitempty"`
	ThreadPlant          []string `protobuf:"bytes,2,rep,name=thread_plant,json=threadPlant" json:"thread_plant,omitempty"`
	ThreadYarn           []string `protobuf:"bytes,3,rep,name=thread_yarn,json=threadYarn" json:"thread_yarn,omitempty"`
	ThreadMetal          []string `protobuf:"bytes,4,rep,name=thread_metal,json=threadMetal" json:"thread_metal,omitempty"`
	ClothSilk            []string `protobuf:"bytes,5,rep,name=cloth_silk,json=clothSilk" json:"cloth_silk,omitempty"`
	ClothPlant           []string `protobuf:"bytes,6,rep,name=cloth_plant,json=clothPlant" json:"cloth_plant,omitempty"`
	ClothYarn            []string `protobuf:"bytes,7,rep,name=cloth_yarn,json=clothYarn" json:"cloth_yarn,omitempty"`
	ClothMetal           []string `protobuf:"bytes,8,rep,name=cloth_metal,json=clothMetal" json:"cloth_metal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_ClothSet) Reset()         { *m = StockpileSettings_ClothSet{} }
func (m *StockpileSettings_ClothSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_ClothSet) ProtoMessage()    {}
func (*StockpileSettings_ClothSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 12}
}
func (m *StockpileSettings_ClothSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_ClothSet.Unmarshal(m, b)
}
func (m *StockpileSettings_ClothSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_ClothSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_ClothSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_ClothSet.Merge(dst, src)
}
func (m *StockpileSettings_ClothSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_ClothSet.Size(m)
}
func (m *StockpileSettings_ClothSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_ClothSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_ClothSet proto.InternalMessageInfo

func (m *StockpileSettings_ClothSet) GetThreadSilk() []string {
	if m != nil {
		return m.ThreadSilk
	}
	return nil
}

func (m *StockpileSettings_ClothSet) GetThreadPlant() []string {
	if m != nil {
		return m.ThreadPlant
	}
	return nil
}

func (m *StockpileSettings_ClothSet) GetThreadYarn() []string {
	if m != nil {
		return m.ThreadYarn
	}
	return nil
}

func (m *StockpileSettings_ClothSet) GetThreadMetal() []string {
	if m != nil {
		return m.ThreadMetal
	}
	return nil
}

func (m *StockpileSettings_ClothSet) GetClothSilk() []string {
	if m != nil {
		return m.ClothSilk
	}
	return nil
}

func (m *StockpileSettings_ClothSet) GetClothPlant() []string {
	if m != nil {
		return m.ClothPlant
	}
	return nil
}

func (m *StockpileSettings_ClothSet) GetClothYarn() []string {
	if m != nil {
		return m.ClothYarn
	}
	return nil
}

func (m *StockpileSettings_ClothSet) GetClothMetal() []string {
	if m != nil {
		return m.ClothMetal
	}
	return nil
}

type StockpileSettings_WoodSet struct {
	Mats                 []string `protobuf:"bytes,1,rep,name=mats" json:"mats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_WoodSet) Reset()         { *m = StockpileSettings_WoodSet{} }
func (m *StockpileSettings_WoodSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_WoodSet) ProtoMessage()    {}
func (*StockpileSettings_WoodSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 13}
}
func (m *StockpileSettings_WoodSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_WoodSet.Unmarshal(m, b)
}
func (m *StockpileSettings_WoodSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_WoodSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_WoodSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_WoodSet.Merge(dst, src)
}
func (m *StockpileSettings_WoodSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_WoodSet.Size(m)
}
func (m *StockpileSettings_WoodSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_WoodSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_WoodSet proto.InternalMessageInfo

func (m *StockpileSettings_WoodSet) GetMats() []string {
	if m != nil {
		return m.Mats
	}
	return nil
}

type StockpileSettings_WeaponsSet struct {
	WeaponType           []string `protobuf:"bytes,1,rep,name=weapon_type,json=weaponType" json:"weapon_type,omitempty"`
	TrapcompType         []string `protobuf:"bytes,2,rep,name=trapcomp_type,json=trapcompType" json:"trapcomp_type,omitempty"`
	OtherMats            []string `protobuf:"bytes,3,rep,name=other_mats,json=otherMats" json:"other_mats,omitempty"`
	Mats                 []string `protobuf:"bytes,4,rep,name=mats" json:"mats,omitempty"`
	QualityCore          []string `protobuf:"bytes,5,rep,name=quality_core,json=qualityCore" json:"quality_core,omitempty"`
	QualityTotal         []string `protobuf:"bytes,6,rep,name=quality_total,json=qualityTotal" json:"quality_total,omitempty"`
	Usable               *bool    `protobuf:"varint,7,opt,name=usable" json:"usable,omitempty"`
	Unusable             *bool    `protobuf:"varint,8,opt,name=unusable" json:"unusable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_WeaponsSet) Reset()         { *m = StockpileSettings_WeaponsSet{} }
func (m *StockpileSettings_WeaponsSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_WeaponsSet) ProtoMessage()    {}
func (*StockpileSettings_WeaponsSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 14}
}
func (m *StockpileSettings_WeaponsSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_WeaponsSet.Unmarshal(m, b)
}
func (m *StockpileSettings_WeaponsSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_WeaponsSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_WeaponsSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_WeaponsSet.Merge(dst, src)
}
func (m *StockpileSettings_WeaponsSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_WeaponsSet.Size(m)
}
func (m *StockpileSettings_WeaponsSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_WeaponsSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_WeaponsSet proto.InternalMessageInfo

func (m *StockpileSettings_WeaponsSet) GetWeaponType() []string {
	if m != nil {
		return m.WeaponType
	}
	return nil
}

func (m *StockpileSettings_WeaponsSet) GetTrapcompType() []string {
	if m != nil {
		return m.TrapcompType
	}
	return nil
}

func (m *StockpileSettings_WeaponsSet) GetOtherMats() []string {
	if m != nil {
		return m.OtherMats
	}
	return nil
}

func (m *StockpileSettings_WeaponsSet) GetMats() []string {
	if m != nil {
		return m.Mats
	}
	return nil
}

func (m *StockpileSettings_WeaponsSet) GetQualityCore() []string {
	if m != nil {
		return m.QualityCore
	}
	return nil
}

func (m *StockpileSettings_WeaponsSet) GetQualityTotal() []string {
	if m != nil {
		return m.QualityTotal
	}
	return nil
}

func (m *StockpileSettings_WeaponsSet) GetUsable() bool {
	if m != nil && m.Usable != nil {
		return *m.Usable
	}
	return false
}

func (m *StockpileSettings_WeaponsSet) GetUnusable() bool {
	if m != nil && m.Unusable != nil {
		return *m.Unusable
	}
	return false
}

type StockpileSettings_ArmorSet struct {
	Body                 []string `protobuf:"bytes,1,rep,name=body" json:"body,omitempty"`
	Head                 []string `protobuf:"bytes,2,rep,name=head" json:"head,omitempty"`
	Feet                 []string `protobuf:"bytes,3,rep,name=feet" json:"feet,omitempty"`
	Hands                []string `protobuf:"bytes,4,rep,name=hands" json:"hands,omitempty"`
	Legs                 []string `protobuf:"bytes,5,rep,name=legs" json:"legs,omitempty"`
	Shield               []string `protobuf:"bytes,6,rep,name=shield" json:"shield,omitempty"`
	OtherMats            []string `protobuf:"bytes,7,rep,name=other_mats,json=otherMats" json:"other_mats,omitempty"`
	Mats                 []string `protobuf:"bytes,8,rep,name=mats" json:"mats,omitempty"`
	QualityCore          []string `protobuf:"bytes,9,rep,name=quality_core,json=qualityCore" json:"quality_core,omitempty"`
	QualityTotal         []string `protobuf:"bytes,10,rep,name=quality_total,json=qualityTotal" json:"quality_total,omitempty"`
	Usable               *bool    `protobuf:"varint,11,opt,name=usable" json:"usable,omitempty"`
	Unusable             *bool    `protobuf:"varint,12,opt,name=unusable" json:"unusable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockpileSettings_ArmorSet) Reset()         { *m = StockpileSettings_ArmorSet{} }
func (m *StockpileSettings_ArmorSet) String() string { return proto.CompactTextString(m) }
func (*StockpileSettings_ArmorSet) ProtoMessage()    {}
func (*StockpileSettings_ArmorSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockpiles_90e17902dad8deef, []int{0, 15}
}
func (m *StockpileSettings_ArmorSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockpileSettings_ArmorSet.Unmarshal(m, b)
}
func (m *StockpileSettings_ArmorSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockpileSettings_ArmorSet.Marshal(b, m, deterministic)
}
func (dst *StockpileSettings_ArmorSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockpileSettings_ArmorSet.Merge(dst, src)
}
func (m *StockpileSettings_ArmorSet) XXX_Size() int {
	return xxx_messageInfo_StockpileSettings_ArmorSet.Size(m)
}
func (m *StockpileSettings_ArmorSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StockpileSettings_ArmorSet.DiscardUnknown(m)
}

var xxx_messageInfo_StockpileSettings_ArmorSet proto.InternalMessageInfo

func (m *StockpileSettings_ArmorSet) GetBody() []string {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *StockpileSettings_ArmorSet) GetHead() []string {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *StockpileSettings_ArmorSet) GetFeet() []string {
	if m != nil {
		return m.Feet
	}
	return nil
}

func (m *StockpileSettings_ArmorSet) GetHands() []string {
	if m != nil {
		return m.Hands
	}
	return nil
}

func (m *StockpileSettings_ArmorSet) GetLegs() []string {
	if m != nil {
		return m.Legs
	}
	return nil
}

func (m *StockpileSettings_ArmorSet) GetShield() []string {
	if m != nil {
		return m.Shield
	}
	return nil
}

func (m *StockpileSettings_ArmorSet) GetOtherMats() []string {
	if m != nil {
		return m.OtherMats
	}
	return nil
}

func (m *StockpileSettings_ArmorSet) GetMats() []string {
	if m != nil {
		return m.Mats
	}
	return nil
}

func (m *StockpileSettings_ArmorSet) GetQualityCore() []string {
	if m != nil {
		return m.QualityCore
	}
	return nil
}

func (m *StockpileSettings_ArmorSet) GetQualityTotal() []string {
	if m != nil {
		return m.QualityTotal
	}
	return nil
}

func (m *StockpileSettings_ArmorSet) GetUsable() bool {
	if m != nil && m.Usable != nil {
		return *m.Usable
	}
	return false
}

func (m *StockpileSettings_ArmorSet) GetUnusable() bool {
	if m != nil && m.Unusable != nil {
		return *m.Unusable
	}
	return false
}

func init() {
	proto.RegisterType((*StockpileSettings)(nil), "dfstockpiles.StockpileSettings")
	proto.RegisterType((*StockpileSettings_AnimalsSet)(nil), "dfstockpiles.StockpileSettings.AnimalsSet")
	proto.RegisterType((*StockpileSettings_FoodSet)(nil), "dfstockpiles.StockpileSettings.FoodSet")
	proto.RegisterType((*StockpileSettings_FurnitureSet)(nil), "dfstockpiles.StockpileSettings.FurnitureSet")
	proto.RegisterType((*StockpileSettings_RefuseSet)(nil), "dfstockpiles.StockpileSettings.RefuseSet")
	proto.RegisterType((*StockpileSettings_StoneSet)(nil), "dfstockpiles.StockpileSettings.StoneSet")
	proto.RegisterType((*StockpileSettings_OreSet)(nil), "dfstockpiles.StockpileSettings.OreSet")
	proto.RegisterType((*StockpileSettings_AmmoSet)(nil), "dfstockpiles.StockpileSettings.AmmoSet")
	proto.RegisterType((*StockpileSettings_CoinSet)(nil), "dfstockpiles.StockpileSettings.CoinSet")
	proto.RegisterType((*StockpileSettings_BarsBlocksSet)(nil), "dfstockpiles.StockpileSettings.BarsBlocksSet")
	proto.RegisterType((*StockpileSettings_GemsSet)(nil), "dfstockpiles.StockpileSettings.GemsSet")
	proto.RegisterType((*StockpileSettings_FinishedGoodsSet)(nil), "dfstockpiles.StockpileSettings.FinishedGoodsSet")
	proto.RegisterType((*StockpileSettings_LeatherSet)(nil), "dfstockpiles.StockpileSettings.LeatherSet")
	proto.RegisterType((*StockpileSettings_ClothSet)(nil), "dfstockpiles.StockpileSettings.ClothSet")
	proto.RegisterType((*StockpileSettings_WoodSet)(nil), "dfstockpiles.StockpileSettings.WoodSet")
	proto.RegisterType((*StockpileSettings_WeaponsSet)(nil), "dfstockpiles.StockpileSettings.WeaponsSet")
	proto.RegisterType((*StockpileSettings_ArmorSet)(nil), "dfstockpiles.StockpileSettings.ArmorSet")
}

func init() { proto.RegisterFile("stockpiles.proto", fileDescriptor_stockpiles_90e17902dad8deef) }

var fileDescriptor_stockpiles_90e17902dad8deef = []byte{
	// 1522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x4f, 0x6f, 0xdb, 0xc6,
	0x13, 0x85, 0x2c, 0xdb, 0xa2, 0x46, 0x7f, 0x6c, 0xf3, 0x97, 0x5f, 0xba, 0x51, 0xea, 0xda, 0xa9,
	0xd3, 0xc4, 0x09, 0x5a, 0xa3, 0xed, 0xa9, 0x40, 0x81, 0x02, 0xb6, 0x8b, 0x24, 0x2d, 0x62, 0x38,
	0x90, 0x0d, 0x18, 0x3d, 0x11, 0x2b, 0x71, 0x25, 0x12, 0x22, 0xb9, 0xca, 0x2e, 0x59, 0xc5, 0xc7,
	0x9e, 0x7b, 0x6b, 0x2f, 0xbd, 0xf6, 0xde, 0x7b, 0x81, 0x7e, 0xaa, 0x7e, 0x84, 0x62, 0x66, 0x96,
	0x12, 0x13, 0xdb, 0xb1, 0x8e, 0x39, 0x69, 0xf7, 0xed, 0x7b, 0xb3, 0x33, 0xc3, 0xd9, 0xdd, 0x11,
	0x6c, 0xda, 0x5c, 0x0f, 0x27, 0xd3, 0x38, 0x51, 0xf6, 0x60, 0x6a, 0x74, 0xae, 0xfd, 0x76, 0x38,
	0x5a, 0x60, 0x9f, 0xfe, 0xfa, 0x00, 0xb6, 0xce, 0xca, 0xe9, 0x99, 0xca, 0xf3, 0x38, 0x1b, 0x5b,
	0xff, 0x7b, 0x68, 0xc8, 0x2c, 0x4e, 0x65, 0x62, 0x45, 0x6d, 0xb7, 0xb6, 0xdf, 0xfa, 0xfa, 0xe9,
	0x41, 0x55, 0x75, 0x70, 0x45, 0x71, 0x70, 0xc8, 0xf4, 0x33, 0x95, 0xf7, 0x4b, 0xa9, 0xff, 0x2d,
	0xac, 0x8e, 0xb4, 0x0e, 0xc5, 0x0a, 0x99, 0x78, 0x7c, 0x9b, 0x89, 0x67, 0x5a, 0x87, 0xa8, 0x27,
	0x91, 0xff, 0x23, 0x34, 0x47, 0x85, 0xc9, 0xe2, 0xbc, 0x30, 0x4a, 0xd4, 0xc9, 0xc2, 0xe7, 0xb7,
	0x5a, 0x28, 0x05, 0x68, 0x66, 0x21, 0xf7, 0x7b, 0xe0, 0x15, 0xd9, 0x24, 0xd3, 0xb3, 0xec, 0x2b,
	0xb1, 0xba, 0x5b, 0xdb, 0x5f, 0xeb, 0xcf, 0xe7, 0xfe, 0x21, 0xac, 0x1b, 0x35, 0x2a, 0xac, 0x12,
	0x6b, 0xb4, 0xc9, 0x93, 0xdb, 0x36, 0xe9, 0x13, 0x1b, 0x77, 0x70, 0x42, 0xff, 0x3b, 0x58, 0xb3,
	0xb9, 0xce, 0x94, 0x58, 0x27, 0x0b, 0xfb, 0xb7, 0x59, 0x38, 0x43, 0x32, 0x1a, 0x60, 0x99, 0xff,
	0x0d, 0xd4, 0xb5, 0x51, 0xa2, 0x41, 0xea, 0x47, 0xb7, 0xa9, 0x4f, 0x39, 0x3c, 0x94, 0x60, 0x86,
	0x65, 0x9a, 0x6a, 0xe1, 0x2d, 0x97, 0xe1, 0xc3, 0x34, 0xd5, 0x94, 0x61, 0x14, 0xa1, 0x78, 0xa8,
	0xe3, 0x4c, 0x34, 0x97, 0x13, 0x1f, 0xeb, 0x38, 0x23, 0x31, 0x8a, 0xfc, 0x13, 0x80, 0x81, 0x34,
	0x76, 0x90, 0xe8, 0xe1, 0xc4, 0x0a, 0x20, 0x13, 0x5f, 0xdc, 0x66, 0xe2, 0x48, 0x1a, 0x7b, 0x44,
	0x0a, 0x34, 0x54, 0x31, 0x80, 0xbe, 0x8c, 0x55, 0x6a, 0x45, 0x6b, 0x39, 0x5f, 0x9e, 0xab, 0x94,
	0x4c, 0x90, 0xc8, 0xbf, 0x80, 0xee, 0x28, 0xce, 0x62, 0x1b, 0xa9, 0x30, 0x18, 0x6b, 0x1d, 0x5a,
	0xd1, 0x26, 0x33, 0x5f, 0xde, 0x5a, 0x2f, 0x4e, 0xf5, 0x1c, 0x45, 0x68, 0xaf, 0x33, 0xaa, 0x22,
	0x78, 0x0c, 0x12, 0x25, 0xf3, 0x48, 0x19, 0xd1, 0x59, 0xee, 0x18, 0xbc, 0x64, 0x3a, 0x1d, 0x03,
	0x27, 0xc5, 0xf2, 0x18, 0x26, 0x3a, 0x8f, 0x44, 0x77, 0xb9, 0xf2, 0x38, 0x46, 0x32, 0x95, 0x07,
	0xc9, 0x30, 0x37, 0x33, 0x3c, 0x46, 0x1b, 0xcb, 0xe5, 0xe6, 0xa2, 0x3c, 0x46, 0x28, 0xc2, 0x10,
	0x66, 0x4a, 0x4e, 0x75, 0x66, 0xc5, 0xe6, 0x72, 0x21, 0x5c, 0x30, 0x9d, 0x42, 0x70, 0x52, 0x0c,
	0x41, 0x9a, 0x54, 0x1b, 0xb1, 0xb5, 0x5c, 0x08, 0x87, 0x48, 0xa6, 0x10, 0x48, 0xe6, 0xef, 0x41,
	0x47, 0x26, 0x89, 0x9e, 0x05, 0xda, 0x8c, 0x65, 0x16, 0x0f, 0x85, 0xbf, 0x5b, 0xdb, 0xf7, 0xfa,
	0x6d, 0x02, 0x4f, 0x19, 0xf3, 0x1f, 0xc3, 0x06, 0x93, 0xe2, 0xac, 0xa4, 0xfd, 0x8f, 0x68, 0x5d,
	0x82, 0x7f, 0x28, 0x51, 0x5f, 0x40, 0x63, 0xa8, 0xcd, 0xd4, 0x2a, 0x2b, 0x04, 0x11, 0xca, 0xa9,
	0xbf, 0x03, 0xad, 0x54, 0xbe, 0x09, 0x06, 0xd2, 0x18, 0x95, 0x58, 0x71, 0x87, 0xce, 0x3a, 0xa4,
	0xf2, 0xcd, 0x11, 0x23, 0xfe, 0x3d, 0xf0, 0x88, 0x10, 0x67, 0x56, 0xfc, 0x9f, 0x56, 0x1b, 0xb8,
	0x1a, 0x67, 0xd6, 0x7f, 0x02, 0x9b, 0xb8, 0x34, 0x8b, 0x94, 0x4a, 0xd0, 0x80, 0x9e, 0x59, 0x71,
	0x97, 0x28, 0x1b, 0xa9, 0x7c, 0x73, 0x51, 0x81, 0xfd, 0x87, 0xd0, 0x2d, 0xac, 0x0a, 0x92, 0x38,
	0x9b, 0xd8, 0x40, 0x67, 0xc9, 0xa5, 0xf8, 0x88, 0xe3, 0x29, 0xac, 0x7a, 0x89, 0xe0, 0x69, 0x96,
	0x5c, 0xf6, 0x22, 0x80, 0xc5, 0xad, 0x88, 0xae, 0xa9, 0x74, 0x9a, 0x5f, 0x06, 0x43, 0x39, 0x56,
	0x7c, 0xad, 0x7a, 0x7d, 0x20, 0xe8, 0x18, 0x91, 0x05, 0x21, 0x37, 0x72, 0x6a, 0xe9, 0xd2, 0x2c,
	0x09, 0xe7, 0x88, 0x60, 0xd8, 0x2a, 0x93, 0x83, 0x44, 0x85, 0xa2, 0xbe, 0x5b, 0xdf, 0x6f, 0xf6,
	0xcb, 0x69, 0xef, 0xdf, 0x55, 0x68, 0xb8, 0xdb, 0xd3, 0xf7, 0x61, 0x35, 0x55, 0x32, 0x17, 0x35,
	0xa2, 0xd0, 0x18, 0xb1, 0x51, 0x6c, 0x23, 0xb1, 0xc2, 0x18, 0x8e, 0x31, 0xdb, 0x45, 0x36, 0x35,
	0x6a, 0x2a, 0x8d, 0x0a, 0x03, 0x5a, 0xbe, 0x43, 0xcb, 0xdd, 0x05, 0xfc, 0x0c, 0x89, 0x9b, 0x50,
	0x57, 0xe3, 0xb1, 0xdb, 0x12, 0x87, 0xfe, 0x5d, 0x58, 0x9f, 0x26, 0x32, 0xcb, 0xad, 0x58, 0x25,
	0xd0, 0xcd, 0x30, 0x82, 0xd0, 0xc4, 0xd9, 0x24, 0xa0, 0xb9, 0x58, 0xa3, 0x45, 0x20, 0xe8, 0x15,
	0x22, 0xfe, 0x03, 0x68, 0x33, 0x81, 0x5f, 0x08, 0xb1, 0x4e, 0x0c, 0x16, 0x71, 0xaa, 0x90, 0x32,
	0x8c, 0x94, 0xb2, 0xca, 0x19, 0x69, 0x30, 0x85, 0x31, 0xb6, 0xb2, 0x07, 0x1d, 0x47, 0x71, 0x66,
	0x3c, 0xe2, 0x38, 0x9d, 0xb3, 0x73, 0x07, 0xd6, 0xac, 0x52, 0xa1, 0x15, 0x4d, 0x5a, 0xe4, 0x09,
	0x7a, 0x9e, 0x28, 0xf9, 0xb3, 0xc2, 0x1b, 0x8b, 0x3c, 0xe7, 0x19, 0xee, 0x3a, 0xd5, 0xb3, 0x50,
	0x19, 0xb7, 0x6b, 0x8b, 0x77, 0x65, 0x8c, 0x77, 0x7d, 0x0c, 0x1b, 0x8e, 0x32, 0x34, 0x4a, 0xd2,
	0xab, 0xd4, 0xe6, 0x7c, 0x31, 0x7c, 0xec, 0x50, 0x4c, 0xf6, 0x38, 0xd1, 0x03, 0xd1, 0xe1, 0x64,
	0xe3, 0xd8, 0xdf, 0x06, 0xc0, 0xdf, 0x60, 0x2a, 0x6d, 0xae, 0x44, 0x97, 0x56, 0x9a, 0x88, 0xbc,
	0x42, 0x00, 0xb7, 0xe7, 0x65, 0xa3, 0xac, 0x55, 0x78, 0xd2, 0x69, 0x7b, 0x22, 0x30, 0x84, 0x94,
	0x24, 0x7e, 0x5d, 0xc4, 0xa1, 0xf3, 0x70, 0x93, 0x29, 0x8c, 0xcd, 0xf3, 0xe2, 0x28, 0x2e, 0x2f,
	0x5b, 0x9c, 0x17, 0x06, 0x5d, 0x5e, 0x76, 0xc0, 0x69, 0x82, 0x34, 0xb6, 0x78, 0x0e, 0xe9, 0x1b,
	0x31, 0x74, 0x12, 0xdb, 0xa1, 0xff, 0x19, 0x74, 0xe7, 0x55, 0x91, 0x2a, 0xec, 0x00, 0xf8, 0x10,
	0x76, 0x4a, 0xf4, 0x04, 0xc1, 0xde, 0x3f, 0x35, 0x68, 0x57, 0x9f, 0x5b, 0x0c, 0x3b, 0xbf, 0x9c,
	0xaa, 0xb2, 0xee, 0x70, 0x8c, 0x61, 0x6b, 0xbc, 0x02, 0x83, 0x54, 0xe6, 0xd6, 0x55, 0x5f, 0x93,
	0x90, 0x13, 0x99, 0x5b, 0x2a, 0x55, 0x5c, 0xa8, 0xbb, 0x52, 0x45, 0xec, 0x01, 0xb4, 0x5f, 0x17,
	0x32, 0x89, 0xf1, 0xa0, 0xe0, 0xa3, 0xc8, 0x15, 0xd6, 0x72, 0xd8, 0x31, 0x3e, 0x7a, 0x7b, 0xd0,
	0x29, 0x29, 0xb9, 0xce, 0x65, 0xe2, 0x0a, 0xad, 0xd4, 0x9d, 0x23, 0xe6, 0xdf, 0x87, 0xa6, 0x95,
	0x59, 0x18, 0x0c, 0xe4, 0xd8, 0xd2, 0xbb, 0xec, 0xf5, 0x3d, 0x04, 0x8e, 0xe4, 0xd8, 0xf6, 0xfe,
	0x5a, 0x81, 0xe6, 0xfc, 0x19, 0xbf, 0xd6, 0xf3, 0xca, 0x15, 0xc3, 0x6e, 0xcf, 0xaf, 0x98, 0x6d,
	0x80, 0x81, 0x0e, 0x2f, 0x83, 0xa9, 0x34, 0x73, 0xd7, 0x9b, 0x88, 0xbc, 0x42, 0x00, 0x2b, 0xcc,
	0x4e, 0x8a, 0x24, 0x99, 0x9f, 0x0d, 0x9e, 0x61, 0x3d, 0x0e, 0x74, 0xa6, 0xac, 0x73, 0x96, 0x27,
	0xb8, 0x75, 0x24, 0x63, 0xe3, 0x0e, 0x02, 0x8d, 0xc9, 0x42, 0xa4, 0xd0, 0x42, 0xc3, 0x59, 0xa0,
	0x19, 0x5a, 0xc8, 0x95, 0xca, 0x23, 0x57, 0xee, 0x3c, 0x41, 0x34, 0xd2, 0x26, 0x9b, 0xd7, 0x39,
	0x4d, 0xf0, 0x82, 0x1a, 0x19, 0x65, 0xa3, 0xc0, 0xc8, 0x59, 0x10, 0xc5, 0xa1, 0xa2, 0x17, 0xda,
	0xeb, 0xb7, 0x09, 0xed, 0xcb, 0xd9, 0x8b, 0x38, 0x54, 0xfe, 0x23, 0xd8, 0x30, 0x3a, 0xcf, 0x55,
	0xb6, 0xa0, 0xb5, 0xf8, 0x5b, 0x33, 0xec, 0x78, 0xbd, 0x4f, 0xc0, 0x2b, 0x5b, 0x96, 0xf9, 0x37,
	0xab, 0x2d, 0xbe, 0x59, 0xef, 0x63, 0x58, 0x3f, 0x35, 0x37, 0xae, 0xfe, 0x51, 0x83, 0x86, 0x6b,
	0x3c, 0x3e, 0xb0, 0x22, 0xe9, 0x6d, 0x43, 0xc3, 0x75, 0x35, 0xd7, 0x7a, 0xfe, 0x67, 0x0d, 0x3a,
	0x6f, 0xb5, 0x2c, 0x98, 0x31, 0x6c, 0x5a, 0x82, 0x8a, 0xc3, 0x2c, 0xe8, 0x20, 0x7c, 0x3a, 0x77,
	0xfa, 0x29, 0x6c, 0x71, 0x63, 0x13, 0x5c, 0x09, 0x6d, 0x83, 0x17, 0x16, 0xdc, 0xfb, 0xd0, 0x24,
	0x9b, 0x95, 0x28, 0x3d, 0x04, 0x68, 0x71, 0x07, 0x5a, 0xce, 0x10, 0x2d, 0x73, 0xa0, 0xc0, 0x10,
	0x12, 0x7a, 0xbf, 0xd7, 0xa0, 0xe1, 0xba, 0x21, 0x7f, 0x1f, 0x36, 0x8d, 0x2e, 0xc6, 0xd1, 0x55,
	0xf7, 0xba, 0x84, 0x2f, 0xf6, 0x7c, 0x08, 0xdd, 0x61, 0x91, 0x5f, 0x75, 0xae, 0x3d, 0x2c, 0xf2,
	0x05, 0x6b, 0x1b, 0x80, 0xed, 0x55, 0x5c, 0x6b, 0x12, 0x42, 0xcb, 0xf7, 0xc0, 0x43, 0x23, 0x15,
	0xc7, 0x1a, 0xc3, 0x22, 0x3f, 0x71, 0x99, 0xdb, 0x7c, 0xb7, 0xb9, 0xfa, 0xd0, 0x3e, 0xfe, 0x2e,
	0xc0, 0xa2, 0x5b, 0xbb, 0xf6, 0xfb, 0xff, 0xb6, 0x02, 0x5e, 0xd9, 0x8c, 0xe1, 0x97, 0xc8, 0x23,
	0xa3, 0x64, 0x18, 0xd8, 0x38, 0x99, 0x38, 0x1e, 0x30, 0x74, 0x16, 0x27, 0x13, 0xf4, 0xcb, 0x11,
	0xf8, 0x86, 0xe6, 0x60, 0x9c, 0x88, 0x6f, 0xe8, 0x85, 0x8d, 0x4b, 0x69, 0x32, 0x17, 0x95, 0xb3,
	0xf1, 0x93, 0x34, 0x59, 0xc5, 0x46, 0xaa, 0xd0, 0xef, 0xd5, 0xaa, 0x8d, 0x13, 0x84, 0x30, 0x63,
	0xd4, 0x16, 0xb2, 0x1b, 0x1c, 0x58, 0x93, 0x10, 0xf2, 0x62, 0x07, 0x5a, 0xbc, 0xcc, 0x4e, 0xf0,
	0xc5, 0xc2, 0x0a, 0xf6, 0x61, 0xae, 0x27, 0x17, 0x1a, 0x15, 0x3d, 0x79, 0x30, 0xd7, 0xb3, 0x03,
	0x5e, 0x45, 0x4f, 0xfb, 0xe3, 0x99, 0xb9, 0xa8, 0xb4, 0x1a, 0xef, 0xe6, 0xec, 0x97, 0x15, 0x80,
	0x45, 0x07, 0x89, 0xe6, 0xb8, 0x87, 0x0c, 0x2a, 0x9f, 0x1e, 0x18, 0x3a, 0xc7, 0x02, 0xd8, 0x83,
	0x0e, 0xf6, 0x3b, 0x43, 0x9d, 0x4e, 0x99, 0xe2, 0x0a, 0xb1, 0x04, 0xcf, 0xaf, 0x56, 0x49, 0xfd,
	0xa6, 0x2a, 0x59, 0x7d, 0x4f, 0x95, 0xac, 0x2d, 0x51, 0x25, 0xeb, 0xd7, 0xbc, 0x23, 0x77, 0x61,
	0xbd, 0xb0, 0xd8, 0x65, 0xd1, 0xdf, 0x33, 0xaf, 0xef, 0x66, 0xfc, 0x97, 0xd2, 0xad, 0x78, 0xfc,
	0xbc, 0x94, 0xf3, 0xde, 0xdf, 0x2b, 0xe0, 0x95, 0x1d, 0x30, 0x3a, 0x87, 0xaf, 0x43, 0x99, 0x24,
	0x1c, 0xd3, 0xb5, 0xaf, 0x64, 0x58, 0xf6, 0x63, 0x38, 0xa6, 0x1e, 0x4d, 0xa9, 0xbc, 0x2c, 0x75,
	0x1c, 0xd3, 0xe5, 0x2e, 0xb3, 0xb0, 0x8c, 0x8c, 0x27, 0xc8, 0x4c, 0xd4, 0xb8, 0x7c, 0x49, 0x68,
	0xcc, 0x8f, 0x46, 0xac, 0x92, 0xd0, 0x05, 0xe1, 0x66, 0xef, 0x64, 0xae, 0x71, 0x53, 0xe6, 0xbc,
	0xf7, 0x64, 0xae, 0xb9, 0x44, 0xe6, 0xe0, 0xbd, 0x99, 0x6b, 0xdd, 0x98, 0xb9, 0xf6, 0xdb, 0x99,
	0x3b, 0x5a, 0x79, 0x51, 0xff, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xf8, 0xcc, 0xd7, 0xb2, 0x10,
	0x00, 0x00,
}
